### ISSUE TITLE
KeyError: 'attachment_0_addr'

### ISSUE THREAD

**Issue by ZhuYuqicheng** [danielhrisca/asammdf#108]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet

 file = r'C:\Users\ZYH7ABT\Desktop\asammdf\demo_error.MF4'

 mf4 = MDF(file)
  
  ## Traceback

  runfile('C:/Users/ZYH7ABT/Desktop/asammdf/test.py', wdir='C:/Users/ZYH7ABT/Desktop/asammdf')
('python=3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 '
 '64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.14.0'
'asammdf=4.5.0'
Traceback (most recent call last):

  File "<ipython-input-4-0bbafdc3978c>", line 1, in <module>
    runfile('C:/Users/ZYH7ABT/Desktop/asammdf/test.py', wdir='C:/Users/ZYH7ABT/Desktop/asammdf')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ZYH7ABT/Desktop/asammdf/test.py", line 30, in <module>
    mf4 = MDF(file)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, memory, **kwargs)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\mdf_v4.py", line 256, in __init__
    self._read()

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\mdf_v4.py", line 492, in _read
    self._read_channels(ch_addr, grp, stream, dg_cntr, ch_cntr, neg_ch_cntr)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1022, in _read_channels
    addr = channel["attachment_0_addr"]

KeyError: 'attachment_0_addr'

# Description

I have problem with import of mf4 file, I always got this key error when I want to import file. But I can quickly import the mf4 file made by asammdf.

Thanks a lot for Help!

**Comment by danielhrisca** [comment]
Hello @ZhuYuqicheng 
Just moments ago I've released version 4.7.0. Can you install it and see if it works correctly?

**Comment by ZhuYuqicheng** [comment]
Hallo @danielhrisca 
I have tried the new version, but I got the same Problem.

**Comment by danielhrisca** [comment]
I guess you use your own file that contains CAN bus logging. Normally the channels should have a link to an attachment (the DBC or ARXML database of CAN messages). 

Can you share the file via e-mail? You can use https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.scramble to generate a scrambled file

**Comment by ZhuYuqicheng** [comment]
no, this mf4 file is the measurement data from vehicle and this have been processed with bdc-file. Should I send you the demo file per E-mail?

**Comment by danielhrisca** [comment]
That would be perfect for debugging. Thank you!

**Comment by ZhuYuqicheng** [comment]
Hallo @danielhrisca ,

It works! I can read the MF4 now!
But when I want to export mat-file, I got this Traceback:

Traceback (most recent call last):

  File "<ipython-input-6-0bbafdc3978c>", line 1, in <module>
    runfile('C:/Users/ZYH7ABT/Desktop/asammdf/test.py', wdir='C:/Users/ZYH7ABT/Desktop/asammdf')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ZYH7ABT/Desktop/asammdf/test.py", line 31, in <module>
    mf4.export('mat', filename = 'demo.mat')

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\mdf.py", line 1431, in export
    included_channels = self._included_channels(i)

  File "C:\Users\ZYH7ABT\AppData\Local\conda\conda\envs\auswerten\lib\site-packages\asammdf\mdf.py", line 440, in _included_channels
    raise MdfException("CAN_DataFrame not found in group " + str(index))

MdfException: CAN_DataFrame not found in group 384

**Comment by ZhuYuqicheng** [comment]
from asammdf import MDF

file = r'C:\Users\ZYH7ABT\Desktop\asammdf\demo_error.MF4'

mf4 = MDF(file)
mf4.export('mat', filename = 'demo')

I have tried these code, and got the same error.

**Comment by danielhrisca** [comment]
I have no errors

```python
from asammdf import MDF
f = '/home/daniel/Downloads/demo.MF4'

mdf = MDF(f)
mdf.export('mat', filename='demo')
print('done')
```
```
done
>>> 
```

Are you sure you have installed the development branch code again?

**Comment by danielhrisca** [comment]
``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``
or
``pip install -I --no-deps git+https://github.com/danielhrisca/asammdf@development``

**Comment by ZhuYuqicheng** [comment]
It works now! Thank you very much!

**Comment by ZhuYuqicheng** [comment]
Hallo @danielhrisca ,

I have Problem again, I can export mat but I can't load it in Matlab because the Variable name length exceed the maximum of Matlab. I can't solve this problem in Matlab, so is there any Way, that a shorter name would be created when export mat file?

**Comment by danielhrisca** [comment]
I was not aware of the maximum variable length for Matlab variables. 
I've made some changes. You should once again install the development branch code and see if it works fine.

**Comment by ZhuYuqicheng** [comment]
It works perfect! Thanks again!
