### ISSUE TITLE
Asammdf not starting

### ISSUE THREAD

**Issue by a543c23** [danielhrisca/asammdf#1086]
# Python version
('python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19043-SP0'
'numpy=1.26.4'
Traceback (most recent call last):
  File "C:\Users\eck\asamdf_test.py", line 15, in <module>
    import asammdf
  File "C:\Program Files\Python39\lib\site-packages\asammdf\__init__.py", line 16, in <module>
    from .gui import plot
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\plot.py", line 8, in <module>
    from .widgets.plot_standalone import PlotWindow
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\widgets\plot_standalone.py", line 8, in <module>
    from .plot import Plot, PlotSignal
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\widgets\plot.py", line 27, in <module>
    from ..utils import FONT_SIZE, value_as_str
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\utils.py", line 230, in <module>
    class QWorkerThread(QtCore.QThread):
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\utils.py", line 242, in QWorkerThread
    _SIGNALS = namedtuple(
  File "C:\Program Files\Python39\lib\collections\__init__.py", line 431, in namedtuple
    __new__ = eval(code, namespace)
NameError: name 'eval' is not defined# Code 

  ## MDF version
  N/A

  ## Code snippet
  asammdf
  
  ## Traceback
  Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\asammdf.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python39\lib\site-packages\asammdf\__init__.py", line 16, in <module>
    from .gui import plot
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\plot.py", line 8, in <module>
    from .widgets.plot_standalone import PlotWindow
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\widgets\plot_standalone.py", line 8, in <module>
    from .plot import Plot, PlotSignal
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\widgets\plot.py", line 27, in <module>
    from ..utils import FONT_SIZE, value_as_str
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\utils.py", line 230, in <module>
    class QWorkerThread(QtCore.QThread):
  File "C:\Program Files\Python39\lib\site-packages\asammdf\gui\utils.py", line 242, in QWorkerThread
    _SIGNALS = namedtuple(
  File "C:\Program Files\Python39\lib\collections\__init__.py", line 431, in namedtuple
    __new__ = eval(code, namespace)
NameError: name 'eval' is not defined
  
# Description
After installing asammdf[gui] 8.0.1 via pip, it does not start.
pip check states that all depedencies are OK.

**Comment by Konzigwenzen** [comment]
I´ve got the same issue.

**Comment by danielhrisca** [comment]
It looks like this only happens on Python 3.9

Can you upgrade to Python 3.10?

**Comment by Konzigwenzen** [comment]
Hi Daniel, thanks for the quick response.

Im using Python 3.11.2.

**Comment by Konzigwenzen** [comment]
Hi Daniel, you are right, with 3.11 it works!

**Comment by a543c23** [comment]
I can confirm. It works with newer python release. 3.12 in my case.
