### ISSUE TITLE
not able to parse .mf4 file

### ISSUE THREAD

**Issue by kalagouda-1008** [danielhrisca/asammdf#1090]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

**Comment by kalagouda-1008** [comment]
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
    
   I executed above code, I got below output:
   ('python=3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 '
 'bit (AMD64)]')
'os=Windows-11-10.0.22631-SP0'
'numpy=1.26.4'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.4.5'

**Comment by danielhrisca** [comment]
please try the development branch code

**Comment by kalagouda-1008** [comment]
I am using development code. still i am getting error.
mdf = MDF(sample_log_file_path)
for above line of code getting below error:
asammdf - ERROR - Error during CAN logging processing: Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 10439, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 10665, in _process_can_logging
    cg_nr = self.append(
            ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 2711, in append
    if self.version >= "4.20" and self._column_storage:
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MDF4' object has no attribute '_column_storage'

**Comment by kalagouda-1008** [comment]
I am using development code. still i am getting error.
mdf = MDF(sample_log_file_path)
for above line of code getting below error:
asammdf - ERROR - Error during CAN logging processing: Traceback (most recent call last):
File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 10439, in _process_bus_logging
self._process_can_logging(index, group)
File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 10665, in _process_can_logging
cg_nr = self.append(
^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 2711, in append
if self.version >= "4.20" and self._column_storage:
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MDF4' object has no attribute '_column_storage'
