### ISSUE TITLE
MDF.extract_bus_logging() issues after 7.3.17 release.

### ISSUE THREAD

**Issue by DanielRaceOn** [danielhrisca/asammdf#1096]
# Python version
('python=3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 '
'bit (AMD64)]')
'os=Windows-10-10.0.26100-SP0'
'numpy=1.26.4'
'asammdf>=7.3.17'

# Code 

  ## MDF version
MDF 4.11

  ## Code snippet
```python
        #Open log file and extract signals from raw bus format
        with MDF(LogFilePath) as mdf:
            log_mdf = mdf.extract_bus_logging(database_files=db_dict)
```
  
  ## Traceback
### 1. issue:
Returns [] instead of mdf object

### 2. issue:
  ```
Traceback (most recent call last):
  File "_root_tests-mdf.py", line 44, in <module>
    log_data_df = can.mdf.get_data(LogFilePath=MDFFilePath, DbFilePath=DBCFilePath2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_root_src\raceoncan\utils\benchmark.py", line 43, in wrapper  
    value = func(*args,**kwargs)
            ^^^^^^^^^^^^^^^^^^^^
  File "_root_src\raceoncan\mdf.py", line 146, in get_data
    log_mdf = mdf.extract_bus_logging(database_files=db_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_root_.venv\Lib\site-packages\asammdf\mdf.py", line 4784, in extract_bus_logging
    out = self._extract_can_logging(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_root_.venv\Lib\site-packages\asammdf\mdf.py", line 5123, in _extract_can_logging
    out.extend(index, sigs)
  File "_root_.venv\Lib\site-packages\asammdf\blocks\mdf_v4.py", line 5833, in extend
    if (origin := invalidation_bits.origin) == InvalidationArray.ORIGIN_UNKNOWN:
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'origin'
```
# Description

The `MDF.extract_bus_logging` function block seems to has been significantly modified in ***7.3.17 release***, but since then, it struggles with extracting some standard raw CAN BUS log file (think it's CSS logger file) and returns empty list.

Other instance of problem is error and traceback when extracting bigger file from Vector software.

**With *asammdf 7.3.16* all works fine** and function returns decoded mdf object in both cases.

Scrambled files can be provided if necessary. 

Best regards, 
Daniel

**Comment by danielhrisca** [comment]
@DanielRaceOn please try the development branch code

**Comment by DanielRaceOn** [comment]
Hi @danielhrisca, thanks for immediate response!
I've tested with ***8.1.0.dev1*** and now in both problematic cases it returns empty MDF object (0 groups):
```
{'version': '4.11', 'program': 'amdf8.1.0.dev1', 'comment': '<HDcomment>\n <TX/>\n <common_properties/>\n</HDcomment>', 'groups': 0}
{'version': '4.10', 'program': 'amdf8.1.0.dev1', 'comment': '<HDcomment>\n <TX/>\n <common_properties/>\n</HDcomment>', 'groups': 0}
```

However, it seems to work fine with some other sample files. 
Let me know if you want to take a look at scrambled files. 

Best regards, 
Daniel

**Comment by MatheusFreitas25** [comment]
Having the same issue here.

**Comment by MatheusFreitas25** [comment]
@DanielRaceOn Did you manage to handle it, or did you find a workaround?

**Comment by danielhrisca** [comment]
Have you tried again then development branch code?

**Comment by DanielRaceOn** [comment]
> @DanielRaceOn Did you manage to handle it, or did you find a workaround?

I stick to version 7.3.17 which seems to work fine with all files I had so far.

**Comment by danielhrisca** [comment]
I need a demo file to debug

**Comment by DanielRaceOn** [comment]
> I need a demo file to debug

Just sent it to your email address.

**Comment by MatheusFreitas25** [comment]
I will try it, thanks!

**Comment by MatheusFreitas25** [comment]
Hello @danielhrisca build wheel is working on master but not on get_bits
[build_asammdf.txt](https://github.com/user-attachments/files/18364005/build_asammdf.txt)

**Comment by MatheusFreitas25** [comment]
Hello @danielhrisca I'm facing this error while building the whl using get_bits branch
[build_asammdf.txt](https://github.com/user-attachments/files/18365274/build_asammdf.txt)


It worked in other branchs

**Comment by danielhrisca** [comment]
please retry with the development branch code
