### ISSUE TITLE
Support optional J1939 PGN conversion for DBC scaling

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#161]
Hi Daniel,

Just wanted to raise a formal feature request on the J1939 DBC scaling we discussed. 

**Feature outline**
A large share of CAN bus applications are based on the J1939 protocol. Here, DBC conversion is not based on the full 29 bit extended CAN ID - but instead only the J1939 PGN subset. 

It would be ideal if asammdf could support DBC scaling for J1939 DBC files by e.g. adding an extra optional input to functions like 'extract_can_logging' and 'get_can_signal' to trigger the use of the J1939 PGN conversion approach.

As discussed, I believe the canmatrix module has been updated accordingly, but if it's not ready then this feature would of course have to be postponed accordingly.

**Sample Data**
Below is a MDF file (MDF 4.11) and 2x demo J1939 DBCs for PGN 61444 (EEC1).

The MDF data is simulated J1939 data in the buslogging format. It includes a number of CAN IDs (all with constant data byte frames), incl. the extended CAN ID CF004FE (which equals PGN 61444).

I've included two DBC demo files, both for PGN 61444. One DBC has an "exact" 29 bit match vs. the MDF file, i.e. it uses CAN ID CF004FE. The other has CAN ID CF00400. Both DBC files should be able to convert the MDF file when correctly utilizing the J1939 PGN match method - but only the CF004FE DBC will work with the regular DBC matching methodology.

If anything is unclear, please let me know. 

[DBC_MDF.zip](https://github.com/danielhrisca/asammdf/files/3073402/DBC_MDF.zip)

**Comment by danielhrisca** [comment]
@MatinF 

please try the development branch code. I was able to extract the EngineSpeed signal using both dbc files.

```python
from asammdf import MDF

mdf = MDF(r'AC6013CD_00003267_00000001.mf4')

mdf.extract_can_logging([r'CSS-Electronics-SAE-J1939-DEMO_CF00400.dbc']).save(r'j1939_dbc.mf4', overwrite=True)

mdf.extract_can_logging([r'CSS-Electronics-SAE-J1939-DEMO_CF00400.dbc']).save(r'regular_dbcmf4', overwrite=True)
```

**Comment by MatinF** [comment]
Hi Daniel,

I tested around with it, but I seem to consistently get the below error:

```
Traceback (most recent call last):
  File "C:\Users\marti\Documents\Code\asammdf-development-test-new\asammdf\get_started_asammdf.py", line 51, in <module>
    mdf_scaled = mdf.extract_can_logging(dbc)
  File "C:\Users\marti\Documents\Code\asammdf-development-test-new\asammdf\asammdf\mdf.py", line 3481, in extract_can_logging
    key="db",
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats.py", line 52, in loads
    return load(fileObject, importType, key, flatImport, **options)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats.py", line 72, in load
    moduleInstance = sys.modules["canmatrix." + importType]
TypeError: can only concatenate str (not "NoneType") to str
```
I ran this with the latest development branch of asammdf, but notice that I did not change anything regarding canmatrix. Do I need to install a specific canmatrix dependency branch to make it work?

Best,
Martin

**Comment by danielhrisca** [comment]
You need to use the latest canmatrix development branch as well

**Comment by MatinF** [comment]
Hi Daniel, I used the latest canmatrix development branch as well as the latest development asammdf branch.

With this, I'm able to convert the full MDF sample I sent you with the full J1939 DBC. 

However, when running the below code I also seem to get a massive printed output with the below repeated hundreds of times, which I believe is also the reason why the code seems to take long to run.

**Code**

```
from asammdf import MDF

mdf = MDF(r"7F34B296_00000008_00000001.mf4")
mdf_scaled = mdf.extract_can_logging(r"CSS-Electronics-SAE-J1939-2018-08_v1.3.dbc")
```


**Output:**

```
dict_keys(['Timestamp', 'CAN_DataFrame', 'CAN_DataFrame.BusChannel', 'CAN_DataFrame.ID', 'CAN_DataFrame.IDE', 'CAN_DataFrame.DLC', 'CAN_DataFrame.DataLength', 'CAN_DataFrame.DataBytes', 'CAN_DataFrame.Dir'])

{486537216, 217056256, 419265536, 418377733, 201326598, 82771974, 418316294, 418377735, 419428357, 417989627, 485229563, 419428377, 417998587, 485238523, 418377762, 419325986, 217977890, 217990180, 418335782, 485230587, 419286054, 484840486, 484844582, 217991217, 419315762, 419428401, 419315767, 419428407, 218051639, 419362887, 419428423, 418024443, 485264379, 218000455, 419428428, 419363911, 419428491, 218101900, 419428492, 217959569, 419315861, 419428501, 419321344, 419428550, 218101973, 417922977, 419286256, 419388656, 419428603, 417988859, 418050299, 485290235, 418024699, 419326208, 419358976, 485264635, 419367171, 419357952, 419362048, 418382086, 419367175, 417997819, 485237755, 419274009, 217977122, 419367203, 419367202, 418370850, 419367206, 484847910, 418382120, 217978146, 217990435, 419335473, 419378482, 419274033, 419367223, 217989431, 419335479, 419378487, 217991495, 419361095, 419367239, 418007035, 484837158, 417922819, 419360256, 419362700, 419367307, 419367308, 419274123, 419286417, 419367317, 419335573, 419378581, 418002939, 485242875, 419362304, 419317529, 419367353, 419367408, 419317542, 484853542, 418030075, 418036219, 485270011, 485276155, 418027003, 419351040, 419361280, 419428864, 419428867, 418031099, 217063941, 217975301, 218102277, 218102278, 419428869, 419428871, 218103299, 218103301, 218103302, 419429893, 484910598, 484910599, 419428883, 285212179, 419429908, 484910612, 419428889, 419429913, 217977378, 419428898, 419428900, 419428899, 484910626, 485246971, 484910627, 419429924, 484910628, 484836902, 486538792, 418316194, 417922978, 419317553, 418316195, 419428913, 419428914, 418317824, 484910641, 419378738, 418316196, 419428919, 419378743, 484910647, 417922981, 418316197, 419428935, 150892103, 418383431, 419343943, 484910663, 419429959, 419429964, 419317559, 419358470, 418316193, 419360512, 419429003, 418326155, 218103436, 484910731, 218103441, 419378837, 485266939, 419362560, 419429062, 218103494, 484910790, 217979605, 418325205, 419429077, 217980629, 217990869, 217054976, 485292803, 419216640, 419347712, 218102512, 419429104, 418316032, 418381568, 417997563, 418030331, 485237499, 485270267, 484910843, 419356416, 485228288, 485293824, 418390784, 419279616, 419265280, 485227267, 217056000, 419429125, 419429126, 419427079, 217989895, 418316035, 419430147, 485227271, 485292807, 418381575, 217054979, 418381573, 419430149, 419317523, 217054981, 418316037, 418381574, 419430150, 485271035, 414318342, 418053894, 419430151, 218103559, 284163847, 414318343, 418316038, 418316039, 217977634, 485227298, 485227299, 485292834, 484870950, 484844326, 417921830, 419427112, 485227302, 485292835, 485292838, 419430180, 418381606, 419430182, 419317544, 419429169, 419388210, 486538034, 419362609, 418381618, 419362585, 218051383, 218102583, 485227319, 485292855, 486538039, 418316086, 217055031, 416350007, 418316087, 418381623, 419427143, 485227335, 485292871, 484910597, 402718535, 418316103, 418381639, 419317575, 419430215, 418316108, 212664083, 218103571, 418316051, 418381587, 419430163, 418316052, 419430164, 486399815, 418316057, 418381593, 485227403, 485227404, 485292939, 485292940, 418316171, 419428236, 218103692, 418316172, 418381707, 418381708, 485227413, 485292949, 418316177, 217055125, 417922965, 418316181, 418316184, 418381717, 419317653, 419362709, 418118561, 418118562, 418184097, 418184098, 418118565, 418184101, 418316066, 418381602, 418381603, 419353856, 419430178, 419430179, 218103586, 218103587, 284163876, 417922851, 418316067, 418316068, 419430384, 484900646, 485227449, 485292985, 418053926, 418316070, 418316217, 418316072, 218102726, 418316230, 419362615, 217980885, 218103765, 418316245, 418381781, 419430357, 418316283, 418381819, 486539259, 218103601, 419429360, 485227504, 485293040, 402718513, 217055026, 418316081, 418316082, 418316272, 419235622, 418381808, 417990651, 418054142} [65528, 61444, 64892, 61184, 0, 61184, 61184, 61184, 65528, 59904, 60416, 65528, 59904, 60416, 61184, 65128, 65044, 65092, 61184, 60416, 64972, 58880, 58880, 65096, 65088, 65528, 65088, 65528, 65332, 65272, 65528, 59904, 60416, 65132, 65528, 65276, 65528, 65528, 65528, 64972, 65088, 65528, 65110, 65528, 65528, 59392, 64972, 65372, 65528, 59904, 59904, 60416, 59904, 65129, 65257, 60416, 65289, 65253, 65269, 61441, 65289, 59904, 60416, 64925, 65041, 65289, 65289, 61184, 65289, 58880, 61441, 65045, 65093, 65165, 65333, 64925, 65289, 65089, 65165, 65333, 65097, 65265, 65289, 59904, 58880, 59392, 65262, 65271, 65289, 65289, 64925, 64973, 65289, 65165, 65333, 59904, 60416, 65270, 65095, 65289, 65289, 65095, 58880, 59904, 59904, 60416, 60416, 59904, 65226, 65266, 65530, 65530, 59904, 61474, 65034, 65530, 65530, 65530, 65530, 65534, 65534, 65534, 65534, 59136, 59136, 65530, 65534, 65534, 59136, 65530, 65534, 65042, 65530, 65530, 65530, 59136, 60416, 59136, 65534, 59136, 58880, 65534, 60928, 59392, 65095, 60928, 65530, 65530, 61184, 59136, 65334, 60928, 65530, 65334, 59136, 59392, 60928, 65530, 65134, 61446, 65198, 59136, 65534, 65534, 65095, 65255, 60928, 65263, 65530, 61184, 65534, 59136, 65534, 65334, 60416, 65271, 65530, 65534, 59136, 65050, 61184, 65530, 65054, 65094, 61184, 60416, 64701, 65213, 65530, 65530, 60928, 61184, 59904, 59904, 60416, 60416, 59136, 65247, 60160, 60416, 61475, 64947, 64891, 60160, 61443, 65531, 65531, 65523, 65091, 60928, 65535, 60160, 60416, 61184, 61184, 61184, 65535, 65095, 61184, 60928, 61184, 65535, 60416, 45312, 59904, 65535, 65535, 61184, 45312, 60928, 60928, 65043, 60160, 60160, 60416, 58880, 58880, 59392, 65523, 60160, 60416, 60416, 65535, 61184, 65535, 65095, 65531, 65371, 65531, 65271, 61184, 65271, 65331, 65531, 60160, 60416, 65531, 60928, 61184, 53248, 60928, 61184, 65523, 60160, 60416, 59136, 0, 60928, 61184, 65095, 65535, 60928, 44032, 65535, 60928, 61184, 65535, 60928, 65535, 64991, 60928, 61184, 60160, 60160, 60416, 60416, 60928, 65527, 65535, 60928, 61184, 61184, 60160, 60416, 60928, 61184, 59392, 60928, 60928, 61184, 65095, 65271, 60160, 60160, 60416, 60416, 60160, 60416, 60928, 61184, 61184, 65237, 65535, 65535, 65535, 65535, 61184, 59392, 60928, 60928, 65535, 58880, 60160, 60416, 59904, 60928, 60928, 60928, 65531, 60928, 65271, 65055, 65535, 60928, 61184, 65535, 60928, 61184, 65535, 65535, 65531, 60160, 60416, 0, 61184, 60928, 60928, 60928, 64775, 61184, 59904, 59904]
61444
```
(the above data chunk is repeated a very large number of times).

Let me know if you have any thoughts on what might be causing this.

Martin

**Comment by MatinF** [comment]
Hi Daniel, I believe this is working as intended now - I'll do some more testing in the coming weeks and let you know if I encounter any issues. Great work as always!

Best,
Martin
