### ISSUE TITLE
GUI  open  file error   

### ISSUE THREAD

**Issue by lonlonago** [danielhrisca/asammdf#198]
2019-06-14, 15:12:28
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\gui\utils.py", line 134, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\blocks\mdf_v4.py", line 248, in __init__
    self._read(mapped=True)
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\blocks\mdf_v4.py", line 456, in _read
    ref_channel = self._ch_map[ch_addr]
KeyError: 0

--------------------------------------------------------------------------------
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\gui\widgets\main.py", line 655, in open_folder
    self._open_file(os.path.join(root, file))
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\gui\widgets\main.py", line 618, in _open_file
    self,
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\gui\widgets\file.py", line 137, in __init__
    progress=progress,
  File "C:\Users\lon\Anaconda3\envs\tf12\lib\site-packages\asammdf\gui\utils.py", line 101, in run_thread_with_progress
    raise Exception(thr.error)

I  use  py3.7  , win10, asammdf 5.9.2, open a *.MF4 file, then get this error.

**Comment by danielhrisca** [comment]
Hello @lonlonago 

I think your file is correputed: it seems that the address of a referenced channel is 0. 

Can you open the file with MDFValidator? It should show this error

**Comment by lonlonago** [comment]
@danielhrisca   I can open it  with MDFValidator without error. but in MDFValidator , there has some unknown messages in MDFValidator, maybe that's why I can not open it with asammdf.exe?

**Comment by danielhrisca** [comment]
please share the MDFValidator printscreen

**Comment by lonlonago** [comment]
![微信图片_20190614153521](https://user-images.githubusercontent.com/15998783/59491950-6d47e400-8eba-11e9-85e6-5bbcd797ad9b.png)
![微信图片_20190614153534](https://user-images.githubusercontent.com/15998783/59491955-6faa3e00-8eba-11e9-8daa-a738240acae5.png)
![微信图片_20190614153557](https://user-images.githubusercontent.com/15998783/59491961-70db6b00-8eba-11e9-915b-44485bcb953a.png)


I can use the GUI open your demo.mf4, but not my own mf4.

**Comment by danielhrisca** [comment]
What are the 2 warnings?

**Comment by lonlonago** [comment]
![微信图片_20190614154338](https://user-images.githubusercontent.com/15998783/59492277-37572f80-8ebb-11e9-88da-df564481f5cb.png)

**Comment by danielhrisca** [comment]
I can't see what is wrong then. Can you send the file for analysis? You can use [scramble](https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.scramble) to hide the internal data

**Comment by lonlonago** [comment]
ok, can you share your email ?

**Comment by danielhrisca** [comment]
daniel.hrisca@gmail.com
