### ISSUE TITLE
some mf4 files doesn't work

### ISSUE THREAD

**Issue by prasad-sawantdesai** [danielhrisca/asammdf#206]
# Python version
_Please run the following snippet and write the output here_
'''
('python=3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.16.4'
'asammdf=5.10.0'```
# Code 

  ## MDF version
  4.1.0

  ## Code snippet
print(MDF(r"C:\KBData\projects\issues\Gor_MF4_Parser_issue\Logging_T024_ToggleTrigger.mf4").version)
  
  ## Traceback
Traceback (most recent call last):
  File "C:/KBData/Data/Development/PyEnSeGiLib/Codebase/ensegilib/evallib/sdfsdf.py", line 21, in <module>
    print(MDF(r"C:\KBData\projects\issues\Gor_MF4_Parser_issue\Logging_T024_ToggleTrigger.mf4").version)
  File "C:\KBApps\python37\env\ensegilib\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\KBApps\python37\env\ensegilib\lib\site-packages\asammdf\blocks\mdf_v4.py", line 249, in __init__
    self._read(mapped=True)
  File "C:\KBApps\python37\env\ensegilib\lib\site-packages\asammdf\blocks\mdf_v4.py", line 497, in _read
    _sig = self.get("CAN_DataFrame", group=i, ignore_invalidation_bits=True)
  File "C:\KBApps\python37\env\ensegilib\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3803, in get
    name, group, index, source=source
  File "C:\KBApps\python37\env\ensegilib\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1930, in _validate_channel_selection
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Channel "CAN_DataFrame" not found in group 31
  
# Description
Hello Daniel,
I am trying to parse some mf4 files which I have. Some can open witout any problem but some has some issue while parsing. Could you please check.

Thank you

**Comment by danielhrisca** [comment]
This might be a file that does not follow the standard. Can you send me the scrambled file for analysis?

**Comment by stlweb** [comment]
@prasad-sawantdesai Maybe your MF4 file is saved message-based, not signal based (by default e.g. CANoe safes mf4-Files message based)

**Comment by prasad-sawantdesai** [comment]
@danielhrisca This file is generated by CANalyzer v 11.0.55. I have attached file here. I shall send you sample file over email.

**Comment by danielhrisca** [comment]
@prasad-sawantdesai 
please try the latest development branch code

**Comment by prasad-sawantdesai** [comment]
@danielhrisca It worked well on latest development branch for the files that I sent you. Thank you for this fix.

I have emailed you some files which are not opening the same way as previous one. May be this issue would be different. Could you please look into the same.
Following is the traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\KBApps\python37\env\prototype\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\KBApps\python37\env\prototype\lib\site-packages\asammdf\blocks\mdf_v4.py", line 249, in __init__

    self._read(mapped=True)
  File "C:\KBApps\python37\env\prototype\lib\site-packages\asammdf\blocks\mdf_v4.py", line 318, in _read
    cg_count, _ = count_channel_groups(stream)
  File "C:\KBApps\python37\env\prototype\lib\site-packages\asammdf\blocks\utils.py", line 670, in count_cha
nnel_groups
    stream.seek(dg_addr + 32)
ValueError: seek out of range
