### ISSUE TITLE
can't run asammdf.exe

### ISSUE THREAD

**Issue by suns07** [danielhrisca/asammdf#219]
C:\Users\zwsun>asammdf.exe
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
asammdf - WARNING - Old pyqtgraph package: Please install the latest pyqtgraph from the github develop branch
pip install -I --no-deps https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\asammdf.exe\__main__.py", line 5, in <module>
  File "c:\python37\lib\site-packages\asammdf\gui\asammdfgui.py", line 7, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "c:\python37\lib\site-packages\asammdf\gui\widgets\main.py", line 18, in <module>
    from .file import FileWidget
  File "c:\python37\lib\site-packages\asammdf\gui\widgets\file.py", line 8, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by nightm4re94** [comment]
It looks like you're missing the psutil module (maybe it's because you're not installing pyqtgraph recursively, but in no-dependency-mode).
Either try 
`pip install psutil`
or use 
`pip install https://github.com/pyqtgraph/pyqtgraph/archive/develop.zip`
for installating pyqtgraph along with all its dependencies, as @danielhrisca advised me to do in #212 .

**Comment by danielhrisca** [comment]
you can also install the extra dependencies needed for GUI

``pip install asammdf[gui]``

this will install **psutil** if it is not already present
