### ISSUE TITLE
Extended arbitration field (over 11bits)

### ISSUE THREAD

**Issue by Jungledede** [danielhrisca/asammdf#226]
# Python version
λ python pythonversion.py
('python=3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.1'
'asammdf=5.10.3'

  ## MDF version
MDF4

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  λ asammdf
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\widgets\main.py", line 603, in open
    self.open_file(event)
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\widgets\main.py", line 640, in open_file
    self._open_file(file_name)
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\widgets\main.py", line 618, in _open_file
    self,
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\widgets\file.py", line 139, in __init__
    progress=progress,
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\utils.py", line 101, in run_thread_with_progress
    raise Exception(thr.error)

<class 'Exception'>: Traceback (most recent call last):
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 582, in _read
    can_msg = db.frameById(message_id)
AttributeError: 'CanMatrix' object has no attribute 'frameById'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\gui\utils.py", line 134, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 249, in __init__
    self._read(mapped=True)
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\asammdf\blocks\mdf_v4.py", line 584, in _read
    can_msg = db.frame_by_id(canmatrix.ArbitrationId(message_id))
  File "<attrs generated init 4c1a9ae1ae3c34c291df9441b2bbf3f0438b65cb>", line 4, in __init__
    self.__attrs_post_init__()
  File "c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages\canmatrix\canmatrix.py", line 600, in __attrs_post_init__
    raise ArbitrationIdOutOfRange('ID out of range')
canmatrix.canmatrix.ArbitrationIdOutOfRange: ID out of range
  
# Description

Hello, i've made a record with VECTOR CanAlyzer v10 sp5 on CAN transmission with Volkswagen product. 2 CAN network on the record, but the ID for the CAN on VW product use the extended ID with 29 bits in place of the standard 11 bits.

Can you implement compatibility for the extend ID ?

**Comment by danielhrisca** [comment]
Hello @Jungledede 

can you confirm that you have _canmatrix 0.8_ installed?

**Comment by danielhrisca** [comment]
also please print the valud of ``message_id`` just before the line that triggers the exception

**Comment by Jungledede** [comment]
Hello,

yes it seems that canmatrix 0.8 is installed.
> λ pip install canmatrix
> Requirement already satisfied: canmatrix in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (0.8)
> Requirement already satisfied: future in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (from canmatrix) (0.17.1)
> Requirement already satisfied: pathlib2 in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (from canmatrix) (2.3.4)
> Requirement already satisfied: attrs>=18.1.0 in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (from canmatrix) (19.1.0)
> Requirement already satisfied: bitstruct in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (from canmatrix) (8.0.0)
> Requirement already satisfied: six in c:\users\rdelente\appdata\local\programs\python\python36\lib\site-packages (from pathlib2-canmatrix) (1.12.0)

I will check to have the value of the message id this afternoon

**Comment by danielhrisca** [comment]
@Jungledede 

please insert this snippet 
```python
                print("All CAN ID's", all_can_ids)
```

here 
https://github.com/danielhrisca/asammdf/blob/development/asammdf/blocks/mdf_v4.py#L663

**Comment by danielhrisca** [comment]
ping @Jungledede 

can you check again with the development branch code ?
