### ISSUE TITLE
Error importing asammdf libraries

### ISSUE THREAD

**Issue by freddyrayes** [danielhrisca/asammdf#246]
# Python version
python=3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]
os=Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid

# Code 

  ## Code snippet
  `import asammdf`
  
  ## Traceback
  ```
Traceback (most recent call last):
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/blocks/utils.py", line 22, in <module>
    from canmatrix.dbc import load as dbc_load
ModuleNotFoundError: No module named 'canmatrix.dbc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/__init__.py", line 15, in <module>
    from .blocks.mdf_v2 import MDF2
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/blocks/mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/blocks/mdf_v3.py", line 40, in <module>
    from ..signal import Signal
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/signal.py", line 9, in <module>
    from .blocks.utils import MdfException, extract_cncomment_xml, SignalSource
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/asammdf/blocks/utils.py", line 26, in <module>
    from canmatrix.formats.arxml import load as arxml_load
  File "/home/<username>/anaconda3/envs/lanedetection/lib/python3.7/site-packages/canmatrix/formats/arxml.py", line 37, in <module>
    from lxml import etree
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

# Description
Using anaconda, I created an environment for py 3.7 and proceeded to install the libraries as specified in the documentation.
```conda install -c conda-forge asammdf```

The error is occuring during the import of the asammdf library, traceback is above. 
importing 'canmatrix' works in python terminal but I don't know why asammdf is seeking 'canmatrix.dbc'

**Comment by danielhrisca** [comment]
Hello Freddy,

what canmatrix version do you have?

**Comment by freddyrayes** [comment]
Daniel,
I have 0.8
```
>>> print (canmatrix.__version__)
0.8
```

**Comment by danielhrisca** [comment]
Do you have lxml installed?

**Comment by freddyrayes** [comment]
yes it's there, version 4.4.1

list of installed libraries:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.7.1                    pypi_0    pypi
asammdf                   5.12.0                     py_0    conda-forge
astor                     0.8.0                    pypi_0    pypi
astroid                   2.2.5                    py37_0  
attrs                     19.1.0                   py37_1  
backcall                  0.1.0                    py37_0  
bitstruct                 8.8.1                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
ca-certificates           2019.9.11            hecc5488_0    conda-forge
canmatrix                 0.8                      pypi_0    pypi
cchardet                  2.1.4            py37hfc679d8_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   py37_0  
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
expat                     2.2.6                he6710b0_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
future                    0.18.0                   py37_0    conda-forge
gast                      0.2.2                    pypi_0    pypi
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.22.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0                    pypi_0    pypi
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      pypi_0    pypi
imageio                   2.5.0                    pypi_0    pypi
imageio-ffmpeg            0.3.0                    pypi_0    pypi
intel-openmp              2019.4                      243  
ipykernel                 5.1.1            py37h39e3cac_0  
ipython                   7.7.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
isort                     4.3.21                   py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.1                    py37_0  
jupyter_client            5.3.1                      py_0  
jupyter_core              4.5.0                      py_0  
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.1.0            py37he6710b0_0  
lazy-object-proxy         1.4.1            py37h7b6447c_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
libxslt                   1.1.32            hae48121_1003    conda-forge
lxml                      4.4.1            py37h7ec2d77_0    conda-forge
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.1.0            py37h5429711_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
moviepy                   1.0.0                    pypi_0    pypi
natsort                   6.0.0                      py_0    conda-forge
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                      pypi_0    pypi
notebook                  6.0.0                    py37_0  
numexpr                   2.7.0            py37hb3f55d8_0    conda-forge
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openssl                   1.1.1c               h516909a_0    conda-forge
pandas                    0.25.1           py37hb3f55d8_0    conda-forge
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.0                      py_0  
pathlib2                  2.3.5                    pypi_0    pypi
pcre                      8.43                 he6710b0_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.1.0                    pypi_0    pypi
pip                       19.1.1                   py37_0  
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.9                    py37_0  
protobuf                  3.9.1                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0  
pygments                  2.4.2                      py_0  
pylint                    2.3.1                    py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.14.11          py37h7b6447c_0  
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    py37_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3                    pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     18.0.0           py37he6710b0_0  
qt                        5.9.7                h5867ecd_1  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.15.0                   pypi_0    pypi
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.3.0                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.29.0               h7b6447c_0  
tensorboard               1.14.0                   pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.3            py37h7b6447c_0  
tqdm                      4.32.2                   pypi_0    pypi
traitlets                 4.3.2                    py37_0  
urllib3                   1.25.3                   pypi_0    pypi
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.15.5                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.2                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.1                he6710b0_3  
zlib                      1.2.11               h7b6447c_3  

```

**Comment by danielhrisca** [comment]
I suggest you re-install lxml

**Comment by freddyrayes** [comment]
reinstalling libiconv using command `conda install -c conda-forge libiconv` seems to have solved it, thanks.
