### ISSUE TITLE
SyntaxError in import module

### ISSUE THREAD

**Issue by white91wolf** [danielhrisca/asammdf#254]
# Python version
_Please run the following snippet and write the output here_

```
'python=2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]'
'os=Windows-10-10.0.18362'
'numpy=1.16.5'
Traceback (most recent call last):
  File "D:\pythonScripts\systemInfo.py", line 15, in <module>
    import asammdf
  File "C:\Python27\lib\site-packages\asammdf\__init__.py", line 15, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Python27\lib\site-packages\asammdf\blocks\mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "C:\Python27\lib\site-packages\asammdf\blocks\mdf_v3.py", line 437
    types.append(("", f"V{gap}"))
                              ^
SyntaxError: invalid syntax
```

# Description

As you can see i get an issue when importing the module. i just installed the module via pip on my windows computer. got no errors or something while installing - also all dependencies where installed.

**Comment by danielhrisca** [comment]
Hello @white91wolf 

starting with version 5.0.0 asammdf requires Python >=3.6. 

This is the last 4.x.y release that you can use with python 2.7 https://pypi.org/project/asammdf/4.7.12
