### ISSUE TITLE
raise ValueError while use cut() function

### ISSUE THREAD

**Issue by StefanLaube96** [danielhrisca/asammdf#266]
## MDF version
5.13.6

  ## Code snippet
mdf_file = MDF('test.mf4')
test = mdf_file.cut(stop=2,whence=1)
  
  ## Traceback
Traceback (most recent call last):
  File "C:\Tools\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d5e12700a72e>", line 1, in <module>
    test = mdf_file.cut(stop=2,whence=1)
  File "C:\Tools\anaconda3\lib\site-packages\asammdf\mdf.py", line 925, in cut
    ignore_invalidation_bits=True,
  File "C:\Tools\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 5044, in get
    vals = fromarrays(arrays, dtype(types))
  File "C:\Tools\anaconda3\lib\site-packages\numpy\core\records.py", line 639, in fromarrays
    raise ValueError("array-shape mismatch in array %d" % k)
ValueError: array-shape mismatch in array 1
  
# Description

I am trying to cut some data out of my mf4-file. Unfortunatly I run in to the error above. I tryied it also with GUI-Version (asammdf.exe) but with the same result.

So far I understand that the cut will be done relative after two seconds?

BR Stefan

**Comment by danielhrisca** [comment]
Hello Ștefan, can you share the scrambled file for analisys?

**Comment by danielhrisca** [comment]
@StefanLaube96 can you try with the development branch code?
