### ISSUE TITLE
error on concatenating filesize more than 4Gb

### ISSUE THREAD

**Issue by sresam89** [danielhrisca/asammdf#275]
# Python version 3.8.0

```
('python=3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit '
'(Intel)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.4'
'asammdf=5.13.16'
```
# Code
```
from asammdf import MDF
from datetime import datetime
import glob

# load MDF/DBC files from an input folder and specify output destination
logfiles = glob.glob("input\*.mf4")
dbc = glob.glob("input\*.dbc")
output_file_dest = "output\output"

def unix_convert(session):
 if dbc:
    mdf = MDF.concatenate(session)
    mdf_scaled = session.extract_can_logging(dbc, "3.0", ignore_invalid_signals=True)
    if mdf_scaled:
        print(mdf_scaled.save(output_file_dest,True))
 else:
    print("No dbc found")


unix_convert(logfiles)  
```

  ## Traceback
```
  Traceback (most recent call last):
  File "convert.py", line 83, in <module>
    unix_convert(session)
  File "convert.py", line 51, in unix_convert
    print(mdf_scaled.save(output_file_dest, True))
  File "/home/test/.local/lib/python3.6/site-packages/asammdf/blocks/mdf_v3.py", line 3396, in save
    write(bytes(block))
  File "/home/test/.local/lib/python3.6/site-packages/asammdf/blocks/v2_v3_blocks.py", line 2406, in __bytes__
    result = pack(fmt, *[self[key] for key in keys])
struct.error: 'I' format requires 0 <= number <= 4294967295
```

  
# Description
i have a folder full of raw mf4 file which I am trying to concatenate. The file grows for more than 4gb in size. at this point the python version of the code break GUI works just fine

Seems like the save function is not able to handle a file of this size

**Comment by danielhrisca** [comment]
Hello @sresam89 the mdf v3 files are limited to 32but addresses, hence you can't perform the concatenation
