### ISSUE TITLE
parameter `remove_source_from_channel_names` throws error when set to true

### ISSUE THREAD

**Issue by pmayd** [danielhrisca/asammdf#286]
# Python version
('python=3.7.6 | packaged by conda-forge | (default, Dec 26 2019, 23:46:52) \n'
 '[Clang 9.0.0 (tags/RELEASE_900/final)]')
'os=Darwin-19.2.0-x86_64-i386-64bit'
'numpy=1.18.1'
'asammdf=5.15.1'
# Code 

  ## MDF version
  4.00

  ## Code snippet
 `mdf = MDF(path, remove_source_from_channel_names=True)`
  
  ## Traceback
  ```
mdf = MDF('992_SEU726_SIt_Mue_2019-09-27_09-34_0013.MF4', remove_source_from_channel_names=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miay/anaconda3/envs/converter/lib/python3.7/site-packages/asammdf/mdf.py", line 128, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "/Users/miay/anaconda3/envs/converter/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 334, in __init__
    self._read(mapped=True)
  File "/Users/miay/anaconda3/envs/converter/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 544, in _read
    ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped
  File "/Users/miay/anaconda3/envs/converter/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 945, in _read_channels
    channel.name, _ = channel.name.split(path_separator, 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
  
# Description

Since latest update of asammdf, above mentioned mdf creation does not work anymore due to ValueError exception during creation of MDF instance. Suggest to wrap this in an try-except block or catch otherwise as it should not lead to program halt.

**Comment by danielhrisca** [comment]
Hello Michael,

please try out the development branch code.

**Comment by pmayd** [comment]
Still the same problem.
Installed with `python setup.py install` from development branch, installing asammdf in version

```
Using /Users/miay/anaconda3/envs/asammdf/lib/python3.7/site-packages
Finished processing dependencies for asammdf==5.15.1
```

```python
>>> mdf = MDF('992_SEU726_SIt_Mue_2019-09-27_09-34_0013.MF4', remove_source_from_channel_names=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miay/work/git/asammdf/asammdf/mdf.py", line 128, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "/Users/miay/work/git/asammdf/asammdf/blocks/mdf_v4.py", line 334, in __init__
    self._read(mapped=True)
  File "/Users/miay/work/git/asammdf/asammdf/blocks/mdf_v4.py", line 544, in _read
    ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped
  File "/Users/miay/work/git/asammdf/asammdf/blocks/mdf_v4.py", line 945, in _read_channels
    channel.name, _ = channel.name.split(path_separator, 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by danielhrisca** [comment]
use this command to install from development

``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by pmayd** [comment]
sorry forget to switch the branch -_-

**Comment by pmayd** [comment]
now using `Finished processing dependencies for asammdf==5.16.0.dev2`

Error is gone!
