### ISSUE TITLE
asammdf GUI fails because of use of depricated time function

### ISSUE THREAD

**Issue by Thor368** [danielhrisca/asammdf#289]
# Python version
python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
os=Windows-10-10.0.18362-SP0
numpy=1.18.1

asammdf release "asammdf-5.15.1-py3-none-any"

  ## Traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\asammdf\__init__.py", line 19, in <module>
    from .gui import plot
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\asammdf\gui\__init__.py", line 1, in <module>
    from .plot import plot
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\asammdf\gui\plot.py", line 6, in <module>
    from .widgets.plot_standalone import PlotWindow
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\asammdf\gui\widgets\plot_standalone.py", line 15, in <module>
    import pyqtgraph as pg
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import *
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'  

# Description
ASAMMDF uses a time function that is declared depricated since python 3.3 and was dropped in 3.8

**Comment by Thor368** [comment]
I just so noticed that actually pyqtgraph actually makes the call. whoopsy.

**Comment by danielhrisca** [comment]
@Thor368 

the error is actually found in the pyqtgraph package and was fixed in their development branch with this PR https://github.com/pyqtgraph/pyqtgraph/pull/980
