### ISSUE TITLE
Attribute Error when closing file

### ISSUE THREAD

**Issue by mikesmitti** [danielhrisca/asammdf#296]
# Python version
_Please run the following snippet and write the output here_
```python
('python=3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.17.4'
'asammdf=5.15.1'
```
# Code 

  ## MDF version
  4.10

  ## Code snippet
mdf.py

line 169

    def __del__(self):
        self.close()
  
  ## Traceback
Traceback (most recent call last):
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\blocks\mdf_v4.py", line 751, in _read
    can_msg = db.frameById(message_id)
AttributeError: 'CanMatrix' object has no attribute 'frameById'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
	..........
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\mdf.py", line 128, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\blocks\mdf_v4.py", line 328, in __init__
    self._read(mapped=False)
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\blocks\mdf_v4.py", line 754, in _read
    canmatrix.ArbitrationId(message_id)
  File "<attrs generated init 4c1a9ae1ae3c34c291df9441b2bbf3f0438b65cb>", line 4, in __init__
  File "C:\__Programme\Python\Python_373\lib\site-packages\canmatrix-0.8-py3.7.egg\canmatrix\canmatrix.py", line 600, in __attrs_post_init__
    raise ArbitrationIdOutOfRange('ID out of range')
canmatrix.canmatrix.ArbitrationIdOutOfRange: ID out of range
Exception ignored in: <function MDF.__del__ at 0x0B2E8E88>
Traceback (most recent call last):
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\mdf.py", line 169, in __del__
    self.close()
AttributeError: 'MDF' object has no attribute 'close'
  
# Description

I got a mf4-file with a message where CANMatrix has problems with an identifier.
Nevertheless, the exceptions way back i get an error when trying to close the file.
The method .close() is not available.
Please take a look at the traceback.

Best regards

**Comment by danielhrisca** [comment]
Hello Mike,

please insert a print at line 754 in mdf_v4.py

```python
                            try:
                                can_msg = db.frameById(message_id)
                            except AttributeError:
                                print('MESSAGE ID', message_id)
                                can_msg = db.frame_by_id(
                                    canmatrix.ArbitrationId(message_id)
                                )
```

**Comment by mikesmitti** [comment]
Hello Daniel,

the console output is:

...
MESSAGE_ID 1514
MESSAGE_ID 2459172864
Traceback (most recent call last):
  File "C:\__Programme\Python\Python_373\lib\site-packages\asammdf-5.15.1-py3.7-win32.egg\asammdf\blocks\mdf_v4.py", line 751, in _read
    can_msg = db.frameById(message_id)
AttributeError: 'CanMatrix' object has no attribute 'frameById'

During handling of the above exception, another exception occurred:
...
 - same like in the initial thread -

**Comment by danielhrisca** [comment]
Thank you, please try the development branch code

**Comment by mikesmitti** [comment]
It works with development branch code and released 5.16.02.

What is happening to the data? When debuging, I did not see data from the file.

Best regards

**Comment by danielhrisca** [comment]
> What is happening to the data? When debuging, I did not see data from the file.

What do you mean? do you have some screenshots?

**Comment by mikesmitti** [comment]
It may be a bit off-topic and only of interest for me:

I do developing/debugging with Eclipse/pydev.
When having a MDF-Object, earlier, I could see the first 300 samples of each channel.
This information I do not find in the objects structure now.

I close the issue, since the original problem is solved.

Best regards.

**Comment by danielhrisca** [comment]
I think you were using _mdfreader_ when the samples. _mdfreader_ loads all the channels in a dict like strcuture; _asammdf_ extracts the channel samples on demand
