### ISSUE TITLE
Module not working when load_measured_data=False

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#3]
Hi Daniel!

When the option load_measured_data is equal to False, the module crashes on line 248 in mdf4.py because it tries to access a value for the key 'data_block' in gp dictionary but the key does not exist.

```bash
Traceback (most recent call last):
  File "C:\Users\gra8hi\Documents\git\asammdf\asammdf\mdf.py", line 48, in __init__
    self.file = MDF4(name, load_measured_data, compression=compression)
  File "C:\Users\gra8hi\Documents\git\asammdf\asammdf\mdf4.py", line 90, in __init__
    self._read(file_stream)
  File "C:\Users\gra8hi\Documents\git\asammdf\asammdf\mdf4.py", line 248, in _read
    ba = bytearray(gp['data_block']['data'][:8])
KeyError: 'data_block'
```

Best, Julien

**Comment by danielhrisca** [comment]
Hi Julien,
That part was used to handle Comments from CANape. Can you post some screenshots from MDFValidator?

**Comment by danielhrisca** [comment]
Please use the latest master and see if the error is fixed

**Comment by JulienGrv** [comment]
Error is fixed.
