### ISSUE TITLE
Calling `to_dataframe()` on MDF version '4.20' fails

### ISSUE THREAD

**Issue by HedgehogCode** [danielhrisca/asammdf#318]
# Python version

Output of the provided snippet:

```
'python=3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) \n[GCC 7.3.0]'
'os=Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid'
'numpy=1.16.1'
'asammdf=5.18.0'
```

# Code 

  ## MDF version

4.20

  ## Code snippet

```python
from asammdf import MDF, Signal

with MDF(version='4.20') as mdf:
    mdf.append(Signal(timestamps=[1, 2], samples=[2, 3], name='a'))
    df = mdf.to_dataframe()
```
  
  ## Traceback

```
Traceback (most recent call last):
  File "mf4_error.py", line 5, in <module>
    df = mdf.to_dataframe()
  File "/home/benjamin/apps/miniconda3/envs/py3_knime_mdf5-18-0/lib/python3.6/site-packages/asammdf/mdf.py", line 3157, in to_dataframe
    validate=True,
  File "/home/benjamin/apps/miniconda3/envs/py3_knime_mdf5-18-0/lib/python3.6/site-packages/asammdf/mdf.py", line 2229, in select
    for idx, sigs in enumerate(self._yield_selected_signals(virtual_group, groups=groups, record_offset=record_offset, record_count=record_count)):
  File "/home/benjamin/apps/miniconda3/envs/py3_knime_mdf5-18-0/lib/python3.6/site-packages/asammdf/blocks/mdf_v4.py", line 7938, in _yield_selected_signals
    _master = self.get_master(index, data=fragments[master_index])
UnboundLocalError: local variable 'master_index' referenced before assignment
```
  
# Description

Calling `to_dataframe()` on an MDF file with version '4.20' fails.

**Comment by danielhrisca** [comment]
Hello Benjamin,

I've pushed a fix to the development branch.

Please note that the support for version '4.20' is only experimental, so you should stick with version '4.11' for real work.

**Comment by HedgehogCode** [comment]
Thank you for the quick response! The fix works :tada:.
