### ISSUE TITLE
UnboundLocalError: local variable 'fmt' referenced before assignment

### ISSUE THREAD

**Issue by Drawodash** [danielhrisca/asammdf#326]
# Python version
'python=2.7.12 (default, Oct  8 2019, 14:14:10) \n[GCC 5.4.0 20160609]'
'os=Linux-4.15.0-88-generic-x86_64-with-Ubuntu-16.04-xenial'
'numpy=1.16.6'
'asammdf=4.7.12'

  ## MDF version
  4.7.12

  ## Code snippet
from asammdf import MDF

def main():
    path_zf = os.path.dirname(os.path.abspath(__file__))+"/InputFiles"
    output_path = os.path.dirname(os.path.abspath(__file__))+"/OutPutFiles"
    file_list = os.listdir(path_zf)
    for fichier in file_list:
        if fichier[-3:] == 'MF4':
            file_path = os.path.join(path_zf, fichier)    
            mf4_to_bag(file_path)

def mf4_to_bag(mf4_path):
    with MDF(mf4_path,memory="low") as yop:
        print yop.get_channel_name(2,2)
        h = yop.get('IMAGE_Frame.Height')
        h.plot()

if __name__ == '__main__':
    main()
    sys.exit(0)
  
  ## Traceback
  File "/home/user/catkin_ws/src/mf4_msgs/test/test.py", line 45, in <module>
    main()

  File "/home/user/catkin_ws/src/mf4_msgs/test/test.py", line 33, in main
    mf4_to_bag(file_path)

  File "/home/user/catkin_ws/src/mf4_msgs/test/test.py", line 39, in mf4_to_bag
    h = yop.get('IMAGE_Frame.Height')

  File "/home/user/.local/lib/python2.7/site-packages/asammdf/blocks/mdf_v4.py", line 4280, in get
    grp["parents"], grp["types"] = self._prepare_record(grp)

  File "/home/user/.local/lib/python2.7/site-packages/asammdf/blocks/mdf_v4.py", line 1827, in _prepare_record
    new_ch.dtype_fmt = get_fmt_v4(data_type, bit_count, ch_type)

  File "/home/user/.local/lib/python2.7/site-packages/asammdf/blocks/utils.py", line 467, in get_fmt_v4
    return fmt

UnboundLocalError: local variable 'fmt' referenced before assignment
  
# Description
i just try to get the data from one channel and i get this error. it's a very stupid error but don't know ow to fix it without break all asammdf import. i  read in a mf4 file that make more than 9GB so i can't upload it.

**Comment by Drawodash** [comment]
i want to precise if i don't use memory="low" in MDF(mf4_path) i get a other error.
Traceback (most recent call last):

  File "/home/yujin/catkin_ws/src/mf4_msgs/test/test.py", line 45, in <module>
    main()

  File "/home/yujin/catkin_ws/src/mf4_msgs/test/test.py", line 33, in main
    mf4_to_bag(file_path)

  File "/home/yujin/catkin_ws/src/mf4_msgs/test/test.py", line 37, in mf4_to_bag
    with MDF(mf4_path) as yop:

  File "/home/yujin/.local/lib/python2.7/site-packages/asammdf/mdf.py", line 127, in __init__
    self._mdf = MDF4(name, memory, **kwargs)

  File "/home/yujin/.local/lib/python2.7/site-packages/asammdf/blocks/mdf_v4.py", line 262, in __init__
    self._read()

  File "/home/yujin/.local/lib/python2.7/site-packages/asammdf/blocks/mdf_v4.py", line 593, in _read
    data = b"".join(cg_data[record_id])

TypeError: sequence item 0: expected string, bytearray found

**Comment by danielhrisca** [comment]
Hello @Drawodash 
I would advise you to install the latest asammdf version, but for this you need to run using Python >= 3.6

**Comment by Drawodash** [comment]
i see but actually i use ROS and i'm not conviced of the compatibility of ROS and Python3.

**Comment by danielhrisca** [comment]
Normally I would not touch the 4.x.y branch, but I've pushed a possible fix for the second error (TypeError: sequence item 0: expected string, bytearray found) and for the initial error you should get a print of the channel that produces the exception that I need to investigate further.
