### ISSUE TITLE
Error opening MDF4 unpack_from requires a buffer of at least 4 bytes

### ISSUE THREAD

**Issue by fredrikjacobson** [danielhrisca/asammdf#328]
# Python version
```
'python=3.7.6 (default, Dec 30 2019, 19:38:28)
'[Clang 11.0.0 (clang-1100.0.33.16)]')
'os=Darwin-18.7.0-x86_64-i386-64bit'
'numpy=1.18.1'
asammdf=5.19.2
```
# Code 

  ## MDF version
4.1

  ## Code snippet
with MDF(name=file_path, version=version) as mdf: 
or open via GUI
  
  ## Traceback
```
 Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 359, in __init__
    self._read(mapped=True)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 737, in _read
    self._sort()
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 9736, in _sort
    new_data, partial_records, cg_size, record_id_nr, _unpack_stuct
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 187, in sort_data_block
    (rec_size,) = UINT32_uf(signal_data, i)
struct.error: unpack_from requires a buffer of at least 4 bytes


Details: 2020-03-13, 09:16:58
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 359, in __init__
    self._read(mapped=True)
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 737, in _read
    self._sort()
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 9736, in _sort
    new_data, partial_records, cg_size, record_id_nr, _unpack_stuct
  File "/usr/local/lib/python3.7/site-packages/asammdf/blocks/mdf_v4.py", line 187, in sort_data_block
    (rec_size,) = UINT32_uf(signal_data, i)
struct.error: unpack_from requires a buffer of at least 4 bytes

--------------------------------------------------------------------------------
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 686, in open
    self.open_file(event)
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 726, in open_file
    self._open_file(file_name)
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/main.py", line 702, in _open_file
    self,
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/widgets/file.py", line 158, in __init__
    progress=progress,
  File "/usr/local/lib/python3.7/site-packages/asammdf/gui/utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```  
# Description

File does not open with asammdf > 5.18.0.
Will send scrambled version by mail.

**Comment by fredrikjacobson** [comment]
![image](https://user-images.githubusercontent.com/8938545/76605846-77fadc80-6511-11ea-8503-9f4b32da7d1e.png)

MDF Validator seems to be able to open file but find errors with respect to HDcomment and FHcomment. Has there been a change in asammdf with regards to this lately?

**Comment by danielhrisca** [comment]
Hello Fredrik,

thank you for the files. I will release a new version with the fix asap

**Comment by fredrikjacobson** [comment]
Works like a charm, thank you
