### ISSUE TITLE
CAN message multiplexing/paging issues

### ISSUE THREAD

**Issue by PhiMun** [danielhrisca/asammdf#337]
# Python version
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.18.1'
'asammdf=5.17.3'

  ## MDF version
  4.11

# Description

Issue #175 says CAN signal multiplexing is available, but I have been unable to get it to work.

I am trying to use the standalone GUI, which I downloaded from here: [https://ci.appveyor.com/project/danielhrisca/asammdf/builds/31444216/job/bmj0kb6h6dlddcw1/artifacts](url) to process a .mf4 file generated by the CANEdge2.

When extracting CAN signals using a .dbc, it seems to disregard multiplexing and get data for each signal from each message, regardless of the multiplexing signal.

I've attached a spreadsheet with an example log of messages and a comparison between what I expect to get and what I actually get, when the example .dbc file is applied to the messages.  The example .dbc was created exactly the same way as the actual file.
[Example files.zip](https://github.com/danielhrisca/asammdf/files/4383467/Example.files.zip)

Am I doing something wrong or is multiplexing non-functional?

**Comment by danielhrisca** [comment]
Did you try with asammdf version 5.19.8?

**Comment by PhiMun** [comment]
I have just tried the latest version of the executable from the link I posted, which is 5.19.3, and it is still a problem.  I am somewhat new to github, so if there is a better place to get the executable than please let me know.

**Comment by danielhrisca** [comment]
https://ci.appveyor.com/project/danielhrisca/asammdf/builds/31672477/job/dl3o3hgxunwn0y7y/artifacts

**Comment by PhiMun** [comment]
The version you linked reads the file as being completely empty.

**Comment by danielhrisca** [comment]
Hello @ebroecker

there is a problem loading the DBC from the archive. The multiplexor signal is not parsed:

```
In [50]: for s in messge:
    ...:     print(s)
    ...:     
page_signal_1
data_2
data_1

In [52]: for s in messge:
    ...:     print(s.multiplex)
    ...:     
Multiplexor
2
1

In [53]: for s in messge:
    ...:     print(s.muxer_for_signal)
    ...:     
None
None
None

In [54]: 
```

**Comment by ebroecker** [comment]
```python
#!/usr/bin/env python3
import canmatrix

db = canmatrix.formats.loadp_flat("ExampleDatabase.dbc")

for f in db.frames:
    for s in f.signals:
        print("{} {}".format(s, s.multiplex))
```

gives me:
```
page_signal_2 Multiplexor
data_5 1
data_4 1
data_3 0
page_signal_1 Multiplexor
data_2 2
data_1 1
```
which looks quite good to me.
muxer_for_signal is only for _complex multiplexed_ frames.

**Comment by danielhrisca** [comment]
Thank you for the info Eduard.

Can you elaborate a bit on the _complex multiplexed_ frames and the usage if muxer_for_signal?

**Comment by ebroecker** [comment]
_complex multiplexed_ means the frame has more than one multiplexer.
If so, a signal can have a link to one multiplexer

**Comment by danielhrisca** [comment]
@ebroecker thank you

@PhiMun @mdiego1595
Please try the development branch code

``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by mdiego1595** [comment]
The development branch works with multiplexed signals.
Thank you

**Comment by PhiMun** [comment]
When I try to open the file I get this error:
```Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 739, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9283, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9352, in _process_can_logging
    assert len(buses) == 1, str(buses)
AssertionError: [1 2]


Details: 2020-03-26, 10:53:23
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 739, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9283, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9352, in _process_can_logging
    assert len(buses) == 1, str(buses)
AssertionError: [1 2]

--------------------------------------------------------------------------------
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 714, in open
    self.open_file(event)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 754, in open_file
    self._open_file(file_name)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 724, in _open_file
    widget = FileWidget(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 153, in __init__
    self.mdf = run_thread_with_progress(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```

**Comment by danielhrisca** [comment]
@PhiMun how about with the new dev code?

**Comment by PhiMun** [comment]
That error was with version 5.20.0.dev7

**Comment by danielhrisca** [comment]
And now you can try 5.20.0.dev8

**Comment by PhiMun** [comment]
I have tried it with 5.20.0.dev8, it was able to load and multiplex a small file (~3 Mb), but failed to load a ~0.5 Gb file, giving me this error:
```Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 739, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9283, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9322, in _process_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1381, in _load_data
    new_data[split_size:],
MemoryError


Details: 2020-03-26, 12:22:02
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 739, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9283, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9322, in _process_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1381, in _load_data
    new_data[split_size:],
MemoryError

--------------------------------------------------------------------------------
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 714, in open
    self.open_file(event)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 754, in open_file
    self._open_file(file_name)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 724, in _open_file
    widget = FileWidget(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 153, in __init__
    self.mdf = run_thread_with_progress(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```
Also, it only loads finalized files, while previous versions (5.17 for sure) were able to open unfinalized .mf4 files.  It either crashes completely without outputting anything or gives this error:
```Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\utils.py", line 1695, in all_blocks_addresses
    for match in re.finditer(pattern, obj)
  File "c:\softwaredocs\python\python38-32\lib\re.py", line 246, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 463, in _read
    addresses = all_blocks_addresses(self._file)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\utils.py", line 1703, in all_blocks_addresses
    for match in re.finditer(pattern, obj.read())
MemoryError


Details: 2020-03-26, 12:26:50
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\utils.py", line 1695, in all_blocks_addresses
    for match in re.finditer(pattern, obj)
  File "c:\softwaredocs\python\python38-32\lib\re.py", line 246, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 463, in _read
    addresses = all_blocks_addresses(self._file)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\utils.py", line 1703, in all_blocks_addresses
    for match in re.finditer(pattern, obj.read())
MemoryError

--------------------------------------------------------------------------------
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 714, in open
    self.open_file(event)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 754, in open_file
    self._open_file(file_name)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 724, in _open_file
    widget = FileWidget(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 153, in __init__
    self.mdf = run_thread_with_progress(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```

**Comment by danielhrisca** [comment]
try dev9

**Comment by PhiMun** [comment]
on dev9:
Still unable to open any unfinalized files.
I was initially able to open a ~0.5 Gb finalized file, but when I tried extracting the CAN signals it gave the below error and has not been able to open any of the ~0.5 Gb files since.  It can still do the 3Mb finalized file though.
```Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 3358, in extract_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1382, in _load_data
    new_data[split_size:],
MemoryError


Details: 2020-03-26, 12:57:09
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 3358, in extract_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1382, in _load_data
    new_data[split_size:],
MemoryError

--------------------------------------------------------------------------------
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 2430, in extract_can_logging
    mdf = run_thread_with_progress(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```
Below is the error it gives me when I try loading the large files after the above error happened.
```
Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 740, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9284, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9323, in _process_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1382, in _load_data
    new_data[split_size:],
MemoryError


Details: 2020-03-26, 13:09:50
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 361, in __init__
    self._read(mapped=False)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 740, in _read
    self._process_bus_logging()
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9284, in _process_bus_logging
    self._process_can_logging(index, group)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9323, in _process_can_logging
    for fragment_index, fragment in enumerate(data):
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1382, in _load_data
    new_data[split_size:],
MemoryError

--------------------------------------------------------------------------------
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 714, in open
    self.open_file(event)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 754, in open_file
    self._open_file(file_name)
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\main.py", line 724, in _open_file
    widget = FileWidget(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\widgets\file.py", line 153, in __init__
    self.mdf = run_thread_with_progress(
  File "c:\softwaredocs\python\python38-32\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)
```
I am going to try a reboot of my PC and will edit with the results.

**Comment by danielhrisca** [comment]
I see you are running on 32bit Python. Can you install a 64 bit version? If the file is 0.5GB raw then it might be possible to run into memory errors.

**Comment by PhiMun** [comment]
I have installed 64 bit Python and it works perfectly on both finalized and unfinalized files of all sizes!  Thanks for all the help!

**Comment by raeez21** [comment]
Hi @danielhrisca  this issue seems to be still present in the latest versions too.
For a timestamp, values are generated for all multiplexed signals irrespective of the value of multiplexer signal.
For eg consider the below picture:
![mux_github](https://user-images.githubusercontent.com/25025418/104709156-95f22880-5744-11eb-822d-485139d94a08.PNG)

The final dataframe contains values for S4 and S5 at timestamp 0 when value of S0 is 0. Ideally there should be values only for S1, S2, S3 at timestamp 0 since value of S0 is 0.

**Comment by danielhrisca** [comment]
@raeez21 I don't see this problem with the files that I have (orange signal is the multiplexor)
![image](https://user-images.githubusercontent.com/20952040/104749290-4d923500-575b-11eb-8c4f-dded29cd012a.png)

Please share a demo file

**Comment by raeez21** [comment]
@danielhrisca Since orange signal is the multiplexor assuming that green and red are the multiplexed signals. What are the mux ids of green and red signal here? Is it 5 and 12 respectively?

**Comment by danielhrisca** [comment]
> What are the mux ids of green and red signal here? Is it 5 and 12 respectively?

Yes, you can find the input files [here](https://github.com/danielhrisca/asammdf/files/4328945/OBD2-DBC-MDF4.zip)

**Comment by raeez21** [comment]
@danielhrisca 
Below is the csv file which I got using extract_can_logging() and to_dataframe().
![excel_results](https://user-images.githubusercontent.com/25025418/104891258-b5808f80-5996-11eb-8178-6396557160a9.PNG)


Here there is some value for S1_PID_05_EngineCoolantTemp column all the time, irrespective of value of ParameterID_Service01 (multiplexor). Actually S1_PID_05_EngineCoolantTemp should only have values when ParameterID_Service01 value is 5 (as mux id for that signal is 5) and all other rows should not be having values (None), right?
Can you pls confirm if my understanding is correct?

**Comment by danielhrisca** [comment]
By default `to_dataframe` performs interpolation. You might want to set `use_interpolation=False` (see https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.to_dataframe)
