### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by tingfenghanlei** [danielhrisca/asammdf#341]
('python=3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 '
 '64 bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.18.2'

Hi, I used the latest version of asammdf, but have the question that：
Traceback (most recent call last):
  File "C:/2019/17HF_jerk/01EPS/venv/matOutput.py", line 2, in <module>
    from asammdf import MDF, Signal
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\asammdf\__init__.py", line 15, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\asammdf\blocks\mdf_v3.py", line 44, in <module>
    from ..signal import Signal
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\asammdf\signal.py", line 9, in <module>
    from .blocks.utils import MdfException, extract_cncomment_xml, SignalSource
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\asammdf\blocks\utils.py", line 27, in <module>
    from cchardet import detect
  File "C:\Users\ZII5SZH\.conda\envs\python36\lib\site-packages\cchardet\__init__.py", line 1, in <module>
    from cchardet import _cchardet
ImportError: DLL load failed: The specified module could not be found.

**Comment by danielhrisca** [comment]
What cChardet version do you have? Does it work with cChardet==2.1.5?

**Comment by tingfenghanlei** [comment]
I just installed the chardet-3.0.4, do you mean this package?

**Comment by danielhrisca** [comment]
no I mean cChardet https://pypi.org/project/cchardet/2.1.5/

**Comment by tingfenghanlei** [comment]
Thank you very much. The error is solved by your method.
