### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Agnon1573** [danielhrisca/asammdf#342]
# Python version
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
```python
('python=3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC '
 'v.1900 64 bit (AMD64)]')
'os=Windows-10-10.0.17763-SP0'
'numpy=1.16.2'
'asammdf=5.12.0'


<class 'Exception'>: Traceback (most recent call last):
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 134, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 263, in __init__
    self._read(mapped=True)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 576, in _read
    _sig = self.get("CAN_DataFrame", group=i, ignore_invalidation_bits=True)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4093, in get
    shape = (total_size,) + channel_values[0].shape[1:]
AttributeError: 'list' object has no attribute 'shape'

**Comment by danielhrisca** [comment]
Hello @Agnon1573 do you still get the error with 5.19.9?

**Comment by Agnon1573** [comment]
Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 362, in __init__
    self._read(mapped=True)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    "CAN_DataFrame", group=i, ignore_invalidation_bits=True
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6423, in get
    master_is_required=master_is_required,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6627, in _get_structure
    record_count=record_count,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6452, in get
    master_is_required=master_is_required,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7428, in _get_scalar
    vals = extract(signal_data, 1)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 159, in extract
    values = array(values)
MemoryError


Details: 2020-04-01, 14:34:16
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 237, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\mdf.py", line 123, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 362, in __init__
    self._read(mapped=True)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    "CAN_DataFrame", group=i, ignore_invalidation_bits=True
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6423, in get
    master_is_required=master_is_required,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6627, in _get_structure
    record_count=record_count,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6452, in get
    master_is_required=master_is_required,
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7428, in _get_scalar
    vals = extract(signal_data, 1)
  File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 159, in extract
    values = array(values)
MemoryError

--------------------------------------------------------------------------------
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 686, in open
    self.open_file(event)
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 726, in open_file
    self._open_file(file_name)
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 702, in _open_file
    self,
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 158, in __init__
    progress=progress,
  File "d:\software\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 202, in run_thread_with_progress
    raise Exception(thr.error)

**Comment by Agnon1573** [comment]
this is use asammdf == 5.19.9

**Comment by danielhrisca** [comment]
in this case I would need your file for analysis

**Comment by danielhrisca** [comment]
> File "d:\software\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 159, in extract

can you  place a ``print(max([len(e) for e in values]))`` before this line?

**Comment by Agnon1573** [comment]
159 lines are commented out

> class MDF4(object):
    """The *header* attibute is a *HeaderBlock*.

    The *groups* attribute is a list of dicts, each one with the following keys:

    * ``data_group`` - DataGroup object
    * ``channel_group`` - ChannelGroup object
    * ``channels`` - list of Channel objects with the same order as found in the mdf file
    * ``channel_dependencies`` - list of *ChannelArrayBlock* in case of channel arrays;
      list of Channel objects in case of structure channel composition
    * ``data_block`` - address of data block
    * ``data_location``- integer code for data location (original file, temporary file or
      memory)
    * ``data_block_addr`` - list of raw samples starting addresses
    * ``data_block_type`` - list of codes for data block type
    * ``data_block_size`` - list of raw samples block size
    * ``sorted`` - sorted indicator flag
    * ``record_size`` - dict that maps record ID's to record sizes in bytes (including invalidation bytes)
    * ``param`` - row size used for tranposizition, in case of tranposed zipped blockss


    Parameters
    ----------
    name : string
        mdf file name (if provided it must be a real file name) or
        file-like object

        * if *full* the data group binary data block will be memorised in RAM
        * if *low* the channel data is read from disk on request, and the
          metadata is memorized into RAM
        * if *minimum* only minimal data is memorized into RAM

    version : string
        mdf file version ('4.00', '4.10', '4.11'); default '4.10'
    callback : function
        keyword only argument: function to call to update the progress; the
        function must accept two arguments (the current progress and maximum
        progress value)
    use_display_names : bool
        keyword only argument: for MDF4 files parse the XML channel comment to
        search for the display name; XML parsing is quite expensive so setting
        this to *False* can decrease the loading times very much; default
        *False*

**Comment by danielhrisca** [comment]
@Agnon1573 can you try again with the development branch code?
