### ISSUE TITLE
Issue with saving mdf from pandas dataframe

### ISSUE THREAD

**Issue by Dauhl** [danielhrisca/asammdf#347]
# Python version
```
'python=3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-7-6.1.7601-SP1'
'numpy=1.18.2'
'asammdf=5.19.14'
'pandas=1.0.3'
```

# Code 
  ## Code snippet
```python
import asammdf
import  pandas as pd
import numpy as np

outputMdf = asammdf.MDF4()

df = pd.DataFrame(index=[1, 2, 3, 4], columns=['ObstacleID'], data=[2, 2, 2, 2])
df.index.name = 'timestamps'
ser = pd.Series(['car', 'car', 'car', 'car'], dtype=np.dtype('|S0'), index=df.index)
df['ObstacleType'] = ser

print(df)
print(df.dtypes)

outputMdf.append(df)
outputMdf.save("output.mf4")

```  
  ## Traceback
```
asammdf - ERROR - Unknown type: dtype=object, shape=(4,)
NoneType: None
Traceback (most recent call last):
  File "C:/Users/test/.PyCharmCE2018.3/config/scratches/scratch_1.py", line 15, in <module>
    outputMdf.append(df)
  File "C:\Users\test\anaconda3\envs\asammdf\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2963, in append
    self._append_dataframe(signals, source_info, units=units)
  File "C:\Users\test\anaconda3\envs\asammdf\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4671, in _append_dataframe
    s_type, s_size = fmt_to_datatype_v4(sig.dtype, sig.shape)
  File "C:\Users\test\anaconda3\envs\asammdf\lib\site-packages\asammdf\blocks\utils.py", line 576, in fmt_to_datatype_v4
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Unknown type: dtype=object, shape=(4,)
```
  
# Description
I want to save a mdf file from a pandas dataframe using the 'append' method. However dataframe columns which are not numbers have the dtype 'object' although specified as byte strings. This raises an 'Unknown type' error. How is it possible to save mdf files which include string channels?

**Comment by danielhrisca** [comment]
Hello @Dauhl 

this will work with asammdf 5.19.16

```python
import asammdf
import pandas as pd
import numpy as np

outputMdf = asammdf.MDF4()

df = pd.DataFrame(index=[1, 2, 3, 4], columns=['ObstacleID'], data=[2, 2, 2, 2])
df.index.name = 'timestamps'
ser = pd.Series(np.array([b'car', b'car', b'car', b'car']), index=df.index)
df['ObstacleType'] = ser

print(df)
print(df.dtypes)


outputMdf.append(df)
outputMdf.save("output.mf4")
```

**Comment by Dauhl** [comment]
Awesome!! Thank you very much for the fast answer and solution!
