### ISSUE TITLE
module conflict

### ISSUE THREAD

**Issue by Chinoizi** [danielhrisca/asammdf#369]
#('python=3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.18.4'
'asammdf=5.20.6'
IDE: Eclipse IDE for C/C++ Developers, Version: 2020-03 (4.15.0), Build id: 20200313-1211
  
Hello,
when i run any script using "from asammdf import MDF", if i have a module called test.py in my project it will be executed before my script

**Comment by danielhrisca** [comment]
The problem seems to come from the package _future_ and only if you have _test.py_ module 

```
Traceback (most recent call last):
  File "scr.py", line 1, in <module>
    from asammdf import MDF
  File "C:\Python37\lib\site-packages\asammdf\__init__.py", line 15, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Python37\lib\site-packages\asammdf\blocks\mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "C:\Python37\lib\site-packages\asammdf\blocks\mdf_v3.py", line 44, in <module>
    from ..signal import Signal
  File "C:\Python37\lib\site-packages\asammdf\signal.py", line 9, in <module>
    from .blocks import v2_v3_blocks as v3b
  File "C:\Python37\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 17, in <module>
    from .utils import get_fields, get_text_v3, MdfException, UINT16_u, UINT16_uf
  File "C:\Python37\lib\site-packages\asammdf\blocks\utils.py", line 29, in <module>
    from canmatrix.dbc import load as dbc_load
  File "C:\Python37\lib\site-packages\canmatrix\__init__.py", line 11, in <module>
    from canmatrix.canmatrix import (
  File "C:\Python37\lib\site-packages\canmatrix\canmatrix.py", line 41, in <module>
    from future.moves.itertools import zip_longest
  File "C:\Python37\lib\site-packages\future\moves\__init__.py", line 8, in <module>
    import_top_level_modules()
  File "C:\Python37\lib\site-packages\future\standard_library\__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "C:\Python37\lib\site-packages\future\standard_library\__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "d:\TMP\test.py", line 1, in <module>
    3/0
ZeroDivisionError: division by zero
```

So you should either make sure not to have a _test.py_ module in the same folder as the running script, or make an issue on the _future_'s repo.
