### ISSUE TITLE
Creating MDF from dataframe with nparray as column

### ISSUE THREAD

**Issue by RobertMouncer** [danielhrisca/asammdf#372]
# Python version
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit ' '(AMD64)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.18.1'
'asammdf=5.20.1'
# Code 

  ## Code snippet
```
     col1 = pd.Series(data=[0,1,2,3,4,5], name='col1')
    test_array = np.array([224, 1, 245, 3, 232, 3])
    col2 = pd.Series(data=[test_array,test_array,test_array,test_array,test_array,test_array], name='col1')
    df = pd.DataFrame()
    df['timestamps'] = col1
    df['CAN_DataFrame.DataBytes'] = col2
    mdf = MDF(df)
```
  
  ## Traceback
```
  Traceback (most recent call last):
  File ".\read - Copy.py", line 42, in <module>
    main_to_mdf1()
  File ".\read - Copy.py", line 38, in main_to_mdf1
    mdf = MDF(df)
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 98, in __init__
    if name:
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 1478, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
  
# Description

I am trying to pass a dataframe with a column that contains np arrays. When doing this I recieve the error shown above. 
My reasoning for wanting to do this is to pass np arrays of CAN data and then use the `extract_can_logging` function to get the real world values. I am able to pass the timestamps and ID but when I create the databytes object and pass them to MDF type, I recieve the error above.

Any help is appreciated.

**Comment by danielhrisca** [comment]
Hello Robert,

what you can do is to just extract the signals from the payload, you can take some hints from [here](https://github.com/danielhrisca/asammdf/blob/master/asammdf/mdf.py#L3463). 

It is not straightforward to add the dataframe to a new MDF and extract the CAN logging. There is a lot of metadata that needs to be set.

Also your code will not work in general. You need to use the _append_ method

```python
mdf = MDF()
mdf.append(df)
```

**Comment by RobertMouncer** [comment]
@danielhrisca yes sorry I noticed that was being used in another issue and  have since updated this issue. Sorry for any confusion. I have updated it to use the append method now but am now recieving the traceback :
```

asammdf - ERROR - Unknown type: dtype=object, shape=(569543,)
NoneType: None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 2532, in append
    self._append_dataframe(signals, source_info, units=units)
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 4251, in _append_dataframe
    s_type, s_size = fmt_to_datatype_v4(sig.dtype, sig.shape)
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\utils.py", line 565, in fmt_to_datatype_v4
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Unknown type: dtype=object, shape=(569543,)
```

**Comment by RobertMouncer** [comment]
I'm also aware that it won't be straightforward.... I have a good idea on how to do it but am just stuck at this hurdle right now :(

**Comment by danielhrisca** [comment]
The DataFrame route will be hard.

You would better downlaod the demo files from [here](https://github.com/danielhrisca/asammdf/issues/357#issuecomment-635919814) and have a look at the channel returned by the code bellow (not the recarray used for the samples, the source attribute).

```python
dbc_files = ['file1.dbc',]
mdf = MDF(demofile)
ch = mdf.get('CAN_DataFrame')
print(ch)
print(ch.samples.dtype)
print(ch.samples.dtype.names)
print(ch.source)
extracted = mdf.extract_can_logging(dbc_files)
```
