### ISSUE TITLE
KeyError: 0 at initialization

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#376]
Hi Daniel,

I have run into a problem in asammdf 5.20.6 with some MDF 4.10 files.

python=3.6.8
asammdf=5.20.6
numpy=1.18.1

I run the following code

```python
import asammdf
mdf = asammdf.MDF('measurement.mf4')
```

and get the following error traceback

```
Traceback (most recent call last):

  File "<ipython-input-10-4827ec6aad43>", line 1, in <module>
    mdf = asammdf.MDF(file)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 121, in __init__
    self._mdf = MDF4(name, **kwargs)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 365, in __init__
    self._read(mapped=True)

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 733, in _read
    self._sort()

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9239, in _sort
    _unpack_stuct,

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 177, in sort_data_block
    rec_size = cg_size[rec_id]

KeyError: 0
```

The files I've tested and that fails in asammdf 5.20.6 **does** work earlier versions, the latest of which I've tested is 5.18.0.
I will send you one of these files by email.

**Comment by danielhrisca** [comment]
Hello Mattias,

the development branch code seems to work with the file. Can you check on your side?

**Comment by morbult** [comment]
Yes, that seems to work fine!

When will you release 5.20.7?
