### ISSUE TITLE
unboundLocalError:local variable 'fmt' referenced before assignment

### ISSUE THREAD

**Issue by Agnon1573** [danielhrisca/asammdf#378]
# Python version
('python=3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC '
 'v.1900 64 bit (AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.19.0'
'asammdf=5.20.6'
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)
4.10
  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
  _please write here the error traceback_
  Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 243, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\mdf.py", line 121, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 365, in __init__
    self._read(mapped=True)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 571, in _read
    ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 926, in _read_channels
    channel.channel_type,
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\utils.py", line 420, in get_fmt_v4
    return fmt
UnboundLocalError: local variable 'fmt' referenced before assignment

Details: 2020-06-29, 21:58:45
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 243, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\mdf.py", line 121, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 365, in __init__
    self._read(mapped=True)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 571, in _read
    ch_addr, grp, stream, dg_cntr, ch_cntr, mapped=mapped
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 926, in _read_channels
    channel.channel_type,
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\blocks\utils.py", line 420, in get_fmt_v4
    return fmt
UnboundLocalError: local variable 'fmt' referenced before assignment

--------------------------------------------------------------------------------
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 822, in open
    self.open_file(event)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 862, in open_file
    self._open_file(file_name)
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\widgets\main.py", line 838, in _open_file
    self,
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\widgets\file.py", line 158, in __init__
    progress=progress,
  File "c:\programdata\anaconda3\lib\site-packages\asammdf\gui\utils.py", line 208, in run_thread_with_progress
    raise Exception(thr.error)

# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

**Comment by danielhrisca** [comment]
@Agnon1573 

does it work with the development branch code? If not please print the arguments passed to the function get_fmt_v4 in mdf_v4.py", line 926,

**Comment by danielhrisca** [comment]
ping @Agnon1573
