### ISSUE TITLE
run get_group() error

### ISSUE THREAD

**Issue by Yuanli-Liu** [danielhrisca/asammdf#392]
when I call  function`get_group()` with parameter 'raster = ts' ( type(ts) is numpy.ndarray ), it runs error.
I got `ts` by `ts = mdf.get(name, group = groupIdx).timestamps`
```
Traceback (most recent call last):
  File "A.py", line 582, in <module>
    group = mdf.get_group(129, channels = None, raster = ts)
  File "/home/procyon/anaconda3/envs/zxl/lib/python3.6/site-packages/asammdf/mdf.py", line 2899, in get_group
    only_basenames=only_basenames,
  File "/home/procyon/anaconda3/envs/zxl/lib/python3.6/site-packages/asammdf/mdf.py", line 3321, in to_dataframe
    interpolate_outwards_with_nan=interpolate_outwards_with_nan,
  File "/home/procyon/anaconda3/envs/zxl/lib/python3.6/site-packages/asammdf/mdf.py", line 3330, in to_dataframe
    if raster:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Then I change `if raster` to `if raster is not None` in `mdf.py`, it ran without error. Is it correct to do this?

**Comment by danielhrisca** [comment]
@Yuanli-Liu 

you are right the check should have been specifically for _None_. I've included the fix in the development branch

**Comment by Yuanli-Liu** [comment]
> @Yuanli-Liu
> 
> you are right the check should have been specifically for _None_. I've included the fix in the development branch

Thanks, the issue solved!
