### ISSUE TITLE
Cannot read MDF4 file

### ISSUE THREAD

**Issue by JulienGrv** [danielhrisca/asammdf#4]
Hi Daniel,

Thank you for your work!
When trying to read an MDF4 file with no options, I got the following error:

```python
>>> import asammdf
>>> mdf = asammdf.MDF('test.MF4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxx\Documents\git\asammdf\asammdf\mdf.py", line 48, in __init__
    self.file = MDF4(name, load_measured_data, compression=compression)
  File "C:\Users\xxxx\Documents\git\asammdf\asammdf\mdf4.py", line 95, in __init__
    self._read(file_stream)
  File "C:\Users\xxxx\Documents\git\asammdf\asammdf\mdf4.py", line 168, in _read
    self._read_channels(ch_addr, grp, file_stream, dg_cntr, ch_cntr)
  File "C:\Users\xxxx\Documents\git\asammdf\asammdf\mdf4.py", line 268, in _read_channels
    sd_block = SignalDataBlock(address=data_list['data_block_addr{}'.format(i)], file_stream=file_stream)
KeyError: 'data_block_addr2'
```

**Comment by danielhrisca** [comment]
Hello Julien,

small error in the handling of number of links. Should be fixed with the latest commit

**Comment by JulienGrv** [comment]
Error fixed, thanks!

**Comment by danielhrisca** [comment]
you will get the same error for default or compression
