### ISSUE TITLE
Memory Error: 5 GB measurement requires more than 24 TiB

### ISSUE THREAD

**Issue by wili91** [danielhrisca/asammdf#407]
# Python version

'python=3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.1'
'asammdf=5.22.0'

# Code 

  ## MDF version
  MDF version = 4.10

  ## Code snippet
 in mdf_v4.py  line 9667

```python
              for bus in buses:
                    idx_ = argwhere(bus_ids == bus).ravel()
                    bus_msg_ids = msg_ids.samples[idx_]

                    bus_t = msg_ids.timestamps[idx_]
                    bus_data_bytes = data_bytes[idx_]

                    unique_ids = sorted(unique(bus_msg_ids).astype("<u8"))

                    bus_map = self.bus_logging_map["CAN"].setdefault(bus, {})

                    for msg_id in unique_ids:
                        bus_map[int(msg_id)] = group_index

                    for msg_id in unique_ids:
                        message = messages.get(msg_id, None)
                        if message is None:
                            continue

                        idx = argwhere(bus_msg_ids == msg_id).ravel()
                        payload = bus_data_bytes[idx]
                        t = bus_t[idx]

                        extracted_signals = extract_mux(
                            payload, message, msg_id, bus, t
                        )

                        for entry, signals in extracted_signals.items():
                            if len(next(iter(signals.values()))["samples"]) == 0:
                                continue
                            if entry not in msg_map:
                                sigs = []

                                for name_, signal in signals.items():
                                    sig = Signal(
                                        samples=signal["samples"],
                                        timestamps=signal["t"],
                                        name=signal["name"],
                                        comment=signal["comment"],
                                        unit=signal["unit"],
                                        invalidation_bits=signal["invalidation_bits"],
                                        display_name=f"CAN{bus}.{message.name}.{signal['name']}",
                                    )

                                    sigs.append(sig)

                                cg_nr = self.append(
                                    sigs,
                                    f"from CAN{bus} message ID=0x{msg_id:X}",
                                    common_timebase=True,
                                )

                                msg_map[entry] = cg_nr

                                self.groups[
                                    cg_nr
                                ].channel_group.comment = f"{message} 0x{msg_id:X}"

                                for ch_index, ch in enumerate(
                                    self.groups[cg_nr].channels
                                ):
                                    if ch_index == 0:
                                        continue

                                    entry = cg_nr, ch_index

                                    name_ = f"{message}.{ch.name}"
                                    self.channels_db.add(name_, entry)

                                    name_ = f"CAN{bus}.{message}.{ch.name}"
                                    self.channels_db.add(name_, entry)

                                    name_ = f"CAN_DataFrame_{msg_id}.{ch.name}"
                                    self.channels_db.add(name_, entry)

                                    name_ = f"CAN{bus}.CAN_DataFrame_{msg_id}.{ch.name}"
                                    self.channels_db.add(name_, entry)

                            else:

                                index = msg_map[entry]

                                sigs = []

                                for name_, signal in signals.items():

                                    sigs.append(
                                        (signal["samples"], signal["invalidation_bits"])
                                    )

                                    t = signal["t"]

                                sigs.insert(0, (t, None))

                                self.extend(index, sigs)
```
  
  ## Traceback

```Traceback (most recent call last):
  File "C:\My\Path\workdir\myprogrammStartpoint.py", line 178, in <module>
    mdfFile = MDFBurner(input_filename)
  File "C:\My\Path\workdir\myprogrammStartpoint.py", line 67, in __init__
    self._load_mdf()
  File "C:\My\Path\workdir\myprogramm.py", line 87, in _load_mdf
    self._mdf = MDF(self._mdf_filepath)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 395, in __init__
    self._read(mapped=True)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    self._process_bus_logging()
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9532, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9677, in _process_can_logging
    bus_data_bytes = data_bytes[idx_]
MemoryError: Unable to allocate 24.2 TiB for an array with shape (455902, 58318980) and data type uint8
```

The error varies for each run. For example I also got 35.9 GiB and 22TiB.
  
# Description

Sadly I cannot provide the original files and code due to regulations. 

However the issue seems to come from deeper down in the asammdf lib anyways. For some reason my 5GB measurment requires a huge chunck of memory. The size required seems to vary during each run. The only part used at this point from the assammdf lib in my code is the MDF(...) constructor.
To me it seems to be some kind of memory leak. 

As for the measurment I am trying to load, I checked it multiple times. It seems to be fine.

During my research I have seen an other issue which seems to be a like for an earlier version of the asammdf lib. Sadly I can not find the issue. I will update this issue if I manage to find it again.

**Comment by wili91** [comment]
MDF File version is 4.10

**Comment by wili91** [comment]
I updated my asammdf lib to the newest version when I did run into this issue #408

**Comment by danielhrisca** [comment]
what is the output of this

```python
print(idx_, idx_.shape)
print(data_bytes, data_bytes.shape)
bus_data_bytes = data_bytes[idx_]
```

**Comment by wili91** [comment]
Sorry, where should I insert the lines of code? I am not sure if I put them in the right section. The errors occurs before I reach those lines.

**Comment by wili91** [comment]
Sorry, now the memory leak is at a different position, the lines you wanted to see are not reached

Traceback (most recent call last):
  File "C:\My\Path\programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 395, in __init__
    self._read(mapped=True)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    self._process_bus_logging()
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9532, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9665, in _process_can_logging
    samples_only=True,
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6078, in get
    vals = vals.copy()
MemoryError: Unable to allocate 39.6 GiB for an array with shape (729, 58318980) and data type uint8

**Comment by danielhrisca** [comment]
please insert this [here](https://github.com/danielhrisca/asammdf/blob/6e6ba51746fce8a9cc608cd013612ef9db92ad83/asammdf/blocks/mdf_v4.py#L9705)

```python
                    print(group.types)
```

**Comment by wili91** [comment]
Here is what I get when inserting the line.

`[('t', '<f8'), ('CAN_DataFrame.ID', '<u4'), ('CAN_DataFrame.Flags', 'u1'), ('CAN_DataFrame.DLC', 'u1'), ('CAN_DataFrame.DataLength', 'u1'), ('CAN_DataFrame.DataBytes', '<u8'), ('invalidation_bytes', 'u1', (0,))]
[     0      1      2 ... 455899 455900 455901] (455902,)
[[230  14 128 ...   0   0   0]
 [ 36 138  18 ...   0   0   0]
 [ 56  74 130 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [ 80 156 242 ...   4   0   0]] (729, 58318980)
Could not afterburn C:/Users/WII2LR/Documents/MessungenProblem/CMP_20200630T100032Z_ZCM-B10_DASy.MF4
Traceback (most recent call last):
  File "C:/My/Path/programm.py", line 178, in <module>
    mdfFile = MDFBurner(input_filename)
  File "C:/My/Path/programm.py", line 67, in __init__
    self._load_mdf()
  File "C:/My/Path/programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 395, in __init__
    self._read(mapped=True)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    self._process_bus_logging()
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9532, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9680, in _process_can_logging
    bus_data_bytes = data_bytes[idx_]
MemoryError: Unable to allocate 24.2 TiB for an array with shape (455902, 58318980) and data type uint8`

**Comment by danielhrisca** [comment]
What about with the change [here]9https://github.com/danielhrisca/asammdf/blob/6e6ba51746fce8a9cc608cd013612ef9db92ad83/asammdf/blocks/mdf_v4.py#L137)

```python
    from .cutils import extract, sort_data_block, lengths, get_vlsd_offsets
    1/0
```

**Comment by wili91** [comment]
These lines are already present.

**Comment by danielhrisca** [comment]
> These lines are already present.

with the 1/0 that would cause a error and make the lib use the pure python functions for sorting?

**Comment by wili91** [comment]
um, no, I thought the 1/0 was some kind of copy paste error. I will try it, and come back to you. 
I am currently trying some patch code suggested by some collegues  in line 155. So It seems to work and prevent the memory leak.  
According to the comment it helps dealing with irregular data. I am not a fan of patching external libraries. 

`            #Temporary solution for irregular data 
            if (str_size == 0 or 256 < str_size) and (pos + 64 < size):
                while str_size != 64:
                    pos = pos+4 
                    (str_size,) = UINT32_uf(signal_data, pos) `

**Comment by wili91** [comment]
For the 1/0 attempt, the memory leak happens aswell. I did remove the patch code for this run:

[('t', '<f8'), ('CAN_DataFrame.ID', '<u4'), ('CAN_DataFrame.Flags', 'u1'), ('CAN_DataFrame.DLC', 'u1'), ('CAN_DataFrame.DataLength', 'u1'), ('CAN_DataFrame.DataBytes', '<u8'), ('invalidation_bytes', 'u1', (0,))]
Traceback (most recent call last):
  File "C:\My\Path\programm.py", line 178, in <module>
    mdfFile = MDFBurner(input_filename)
  File "C:\My\Path\programm.py", line 67, in __init__
    self._load_mdf()
  File "C:\My\Path\programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 396, in __init__
    self._read(mapped=True)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 772, in _read
    self._process_bus_logging()
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9533, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9667, in _process_can_logging
    samples_only=True,
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6079, in get
    vals = vals.copy()
MemoryError: Unable to allocate 39.6 GiB for an array with shape (729, 58318980) and data type uint8

**Comment by danielhrisca** [comment]
>         #Temporary solution for irregular data 
>         if (str_size == 0 or 256 < str_size) and (pos + 64 < size):
>             while str_size != 64:
>                 pos = pos+4 
>                 (str_size,) = UINT32_uf(signal_data, pos)

This looks a dumb recording application: using signal data blocks for the CAN payload, then setting each sample size to the DLC value and actually using 64 bytes on disk regardless.

**Comment by danielhrisca** [comment]
can you show in mdfvalidator the databytes channel and its signal data block?

![image](https://user-images.githubusercontent.com/20952040/93193508-9d320700-f74f-11ea-8d8e-8b5bcca144ff.png)
![image](https://user-images.githubusercontent.com/20952040/93193527-a327e800-f74f-11ea-9011-d4859984655c.png)

**Comment by danielhrisca** [comment]
and please add this here https://github.com/danielhrisca/asammdf/blob/6e6ba51746fce8a9cc608cd013612ef9db92ad83/asammdf/blocks/mdf_v4.py#L148

```python
        print(signal_data[:256].hex())
```

**Comment by wili91** [comment]
For line 148 I get the following out put:
40000000e60e800500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000248a12c496600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000384a82c356311e78000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000640a8d6f0000200000000000000000000000000000000000000000000000000000000000000000000000000000000000

Traceback (most recent call last):
  File "C:\My\Path\programm.py", line 178, in <module>
    mdfFile = MDFBurner(input_filename)
  File "C:\My\Path\programm.py", line 67, in __init__
    self._load_mdf()
  File "C:\My\Path\programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\Users\WII2LR\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 395, in __init__
    self._read(mapped=True)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 771, in _read
    self._process_bus_logging()
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9532, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9666, in _process_can_logging
    samples_only=True,
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6078, in get
    vals = vals.copy()
MemoryError: Unable to allocate 39.6 GiB for an array with shape (729, 58318980) and data type uint8

**Comment by danielhrisca** [comment]
Can you also share the mdfvalidator screen shots?

**Comment by danielhrisca** [comment]
one more thing , can you insert a print here https://github.com/danielhrisca/asammdf/blob/103bcb2bbb3fa19b275d271826d0a13b7c6049fd/asammdf/blocks/mdf_v4.py#L7081

```python
            print(vals)
```

**Comment by wili91** [comment]
hi daniel,
a collegue of mine sent you the screenshots yesterday per mail. MDF Validator keeped crashing on my pc. So he helped me out.  
As for the traceback you wanted:

[('t', '<f8'), ('f1', 'V3'), ('CAN_DataFrame.IDE', 'u1'), ('CAN_DataFrame.Flags', 'u1'), ('CAN_DataFrame.DLC', 'u1'), ('CAN_DataFrame.DataLength', 'u1'), ('CAN_DataFrame.DataBytes', '<u8'), ('invalidation_bytes', 'u1', (0,))]
---------------vals-----------------------
[      0      68     136 ... 1012928 1012996 1013064]
signal data:
40000000e60e800500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000e700800500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000ba018005000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000005d0280050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Bus index:
[    0     1     2 ... 14896 14897 14898] (14899,)
Data Bytes:
[[230  14 128 ...   0   0   0]
 [231   0 128 ...   0   0   0]
 [186   1 128 ...   0   0   0]
 ...
 [230  14 128 ...   0   0   0]
 [231   0 128 ...   0   0   0]
 [ 40 221 106 ...  40  32 169]] (1011, 944928)
Traceback (most recent call last):
  File "C:\My\Path\programm.py", line 178, in <module>\
    mdfFile = MDFBurner(input_filename)
  File "C:\My\Path\programm.py", line 67, in __init__
    self._load_mdf()
  File "C:\My\Path\programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 125, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 396, in __init__
    self._read(mapped=True)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 772, in _read
    self._process_bus_logging()
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9535, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9685, in _process_can_logging
    bus_data_bytes = data_bytes[idx_]
IndexError: index 1011 is out of bounds for axis 0 with size 1011
