### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ecus'

### ISSUE THREAD

**Issue by wili91** [danielhrisca/asammdf#408]
# Python version
'python=3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.17763-SP0'
'numpy=1.19.1'
'asammdf=5.9.0'

# Code 

  ## MDF version
  MDF Version: 4.10

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback

Traceback (most recent call last):

  File "C:/My/Path/programm.py", line 87, in _load_mdf
    print(MDF(self._mdf_filepath).version)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\mdf.py", line 126, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 248, in __init__
    self._read(mapped=True)
  File "C:\My\Path\\.conda\envs\afterburner\lib\site-packages\asammdf\blocks\mdf_v4.py", line 511, in _read
    board_units = set(bu.name for bu in db.ecus)
AttributeError: 'NoneType' object has no attribute 'ecus'
  
# Description
This issue occures when trying to load an MDF file.  The MDF file is ok. 
The traceback is missleading. The actual error occures in line 508.  `db = load_can_database(at_name, attachment)`
For some reason opening the attachment does not work out.  And the db type is None.

**Comment by danielhrisca** [comment]
> 'asammdf=5.9.0'

Please try with the development branch code

**Comment by wili91** [comment]
I tried using the 5.22.0 version. It did result in another issue. But ofcouse I can try the development branch aswell
