### ISSUE TITLE
MemoryError in mdf.append

### ISSUE THREAD

**Issue by haipas** [danielhrisca/asammdf#412]
# Python version
('python=3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit '
 '(Intel)]')
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.2'
'asammdf=5.22.0'

# Code 

  ## MDF version
  4.10

  ## Code snippet
```
from asammdf import MDF, Signal
import numpy as np

def mdf_size_test(data_type: str, size: int):
    mdf = MDF()
    value = np.arange(size, dtype=np.dtype(data_type))
    timestamp = np.arange(value.size)
    sig = Signal(samples=value, name='test', timestamps=timestamp)

    print("Signal %6.6f MB" %((value.size * value.itemsize)/1000/1000))
    print("Timestamp %6.6f MB" % ((timestamp.size * timestamp.itemsize)/1000/1000))

    mdf.append([sig])
    mdf.save(data_type + '.mdf4', overwrite=True)



if __name__ == "__main__":

    mdf_size_test('int8', 46560000) # 46500000
    # mdf_size_test('int16', 38000000)
    # mdf_size_test('int32', 30000000)
    # mdf_size_test('float32', 30000000)
    # mdf_size_test('float64', 20000000)
```
  
  ## Traceback
C:\Users\ph\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py
Signal 46.560000 MB
Timestamp 186.240000 MB
Traceback (most recent call last):
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 25, in <module>
    mdf_size_test('int8', 46560000)
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 19, in mdf_size_test
    mdf.append([sig])
  File "C:\Users\ph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3307, in append
    data = lz_compress(data)
MemoryError
  
# Description

Hello,
I'm trying to save data from another source to a MDF4 file. But I have the problem that I can't save vectors where the signal + timestamp is bigger than ~232MB.

Is it possible to increase this limit to the 32bit limit (~4GB)?

**Comment by danielhrisca** [comment]
The OS automatically handles this, it cannot be controlled from the Python application.

can you try this to free some memory? 

```python
                data = samples.tobytes()
                del samples
                raw_size = len(data)
                data = lz_compress(data)
```

**Comment by haipas** [comment]
I tried it and the result is that the vector size was increased to ~300MB.

**Comment by danielhrisca** [comment]
please try the development branch code

**Comment by haipas** [comment]
now i get the following error

```
C:\Users\ph\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py
Signal 46.500000 MB
Timestamp 186.000000 MB
Traceback (most recent call last):
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 25, in <module>
    mdf_size_test('int8', 46500000) # 46500000
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 20, in mdf_size_test
    mdf.save(data_type + '.mdf4', overwrite=True)
  File "C:\Users\ph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 8536, in save
    for i, data__ in enumerate(data):
  File "C:\Users\ph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 1271, in _load_data
    new_data = lz_decompress(new_data)
RuntimeError: Frame incomplete. LZ4F_decompress returned: 13

Process finished with exit code 1
```

**Comment by danielhrisca** [comment]
please try again with the new changes

**Comment by haipas** [comment]
I have tried the new version. The available memory size has increased about 30%.
If the vector gets too big I get the following error.

```
C:\Users\ph\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py
Signal 71.525574 MB
Timestamp 286.102295 MB
Traceback (most recent call last):
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 25, in <module>
    mdf_size_test('int8', 75000000)  # 74000000 ->works
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 19, in mdf_size_test
    mdf.append([sig])
  File "C:\Users\ph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3306, in append
    data = samples.tobytes()
MemoryError

Process finished with exit code 1
```

**Comment by danielhrisca** [comment]
please check the new code

**Comment by haipas** [comment]
i get the following error.

```
C:\Users\ph\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py
Signal 71.525574 MB
Timestamp 286.102295 MB
Traceback (most recent call last):
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 25, in <module>
    mdf_size_test('int8', 75000000)  # 74000000 ->works
  File "C:/Users/ph/Documents/analyzer_dll_python/mdf_test.py", line 19, in mdf_size_test
    mdf.append([sig])
  File "C:\Users\ph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asammdf\blocks\mdf_v4.py", line 3314, in append
    chunk = ceil(_20MB / samples.itemsize)
UnboundLocalError: local variable 'samples' referenced before assignment

Process finished with exit code 1
```

**Comment by danielhrisca** [comment]
🤦 yeah please try again

**Comment by haipas** [comment]
That looks good. The limit is now at about 400MB, so it is feeling like it is not a hard limit, it depends on the operating system.  For me the limit is now enough.
Many thanks 👍

**Comment by danielhrisca** [comment]
this is as much as I can do. For large data (many signals or high number of samples) you can still get a memory error here https://github.com/danielhrisca/asammdf/blob/536dd4e8d56ac54bf49eae6df9905c45dfcba5f9/asammdf/blocks/mdf_v4.py#L3295
