### ISSUE TITLE
Error while converting signal to Pandas

### ISSUE THREAD

**Issue by cultur98** [danielhrisca/asammdf#424]
# Python version
'python=3.8.2 (default, Jul 16 2020, 14:00:26) \n[GCC 9.3.0]'
'os=Linux-5.4.0-48-generic-x86_64-with-glibc2.29'
'numpy=1.19.1'
'asammdf=5.23.1'

# Code 
```
from asammdf import MDF
import pandas as pd

print(MDF("test.mf4").version)
mdf_data = MDF("test.mf4")
group_count = len(mdf_data.masters_db.keys())

iterator_groups = mdf_data.iter_groups(ignore_value2text_conversions=True) 

for i in range(0, group_count):
    print("\nconvert to pandas:")
    pandas_df = next(iterator_groups)
```
# Output 
At a certain time I get:
```
convert to pandas:
Traceback (most recent call last):
  File "bugtest1.py", line 12, in <module>
    pandas_df = next(iterator_groups)
  File "/home/harpoo/.local/lib/python3.8/site-packages/asammdf/mdf.py", line 2080, in iter_groups
    yield self.get_group(
  File "/home/harpoo/.local/lib/python3.8/site-packages/asammdf/mdf.py", line 2909, in get_group
    return self.to_dataframe(
  File "/home/harpoo/.local/lib/python3.8/site-packages/asammdf/mdf.py", line 3371, in to_dataframe
    result = mdf.to_dataframe(
  File "/home/harpoo/.local/lib/python3.8/site-packages/asammdf/mdf.py", line 3548, in to_dataframe
    for name, series in components(
  File "/home/harpoo/.local/lib/python3.8/site-packages/asammdf/blocks/utils.py", line 1134, in components
    values = Series(
  File "/home/harpoo/.local/lib/python3.8/site-packages/pandas/core/series.py", line 244, in __init__
    raise ValueError(
ValueError: Cannot construct a Series from an ndarray with compound dtype.  Use DataFrame instead.
```

**Comment by danielhrisca** [comment]
@cultur98 have you tried the development branch code?

**Comment by cultur98** [comment]
Yes I did. And this fixed the Problem for me. Thanks Daniel!

**Comment by danielhrisca** [comment]
Great
