### ISSUE TITLE
unable to execute asammdf.exe 

### ISSUE THREAD

**Issue by Lawa121** [danielhrisca/asammdf#432]
# Python version
_Please run the following snippet and write the output here_
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32

('python=3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 '
 '64 bit (AMD64)]')

'os=Windows-10-10.0.18362-SP0'

'numpy=1.19.2'

'asammdf=5.23.1'

# Code 

 NONE
  
# Description

Hello there,

I do have a problem when I want to open the asammdf.exe file. A doubleclick on the file does nothing but opening and closing the command line quickly. 

The command line input (C:\Users\Scripts>asammdf.exe) led to the following message:

Traceback (most recent call last):
  File "C:\Users\Scripts\asammdf-script.py", line 5, in <module>
    from asammdf.gui.asammdfgui import main
  File "C:\Users\lib\site-packages\asammdf\__init__.py", line 15, in <module>
    from .blocks.mdf_v2 import MDF2
  File "C:\Users\lib\site-packages\asammdf\blocks\mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "C:\Users\lib\site-packages\asammdf\blocks\mdf_v3.py", line 17, in <module>
    from numpy import (
  File "C:\Users\lib\site-packages\numpy\__init__.py", line 143, in <module>
    from . import lib
  File "C:\Users\lib\site-packages\numpy\lib\__init__.py", line 25, in <module>
    from .index_tricks import *
  File "C:\Users\lib\site-packages\numpy\lib\index_tricks.py", line 11, in <module>
    import numpy.matrixlib as matrixlib
  File "C:\Users\lib\site-packages\numpy\matrixlib\__init__.py", line 4, in <module>
    from .defmatrix import *
  File "C:\Users\lib\site-packages\numpy\matrixlib\defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "C:\Users\lib\site-packages\numpy\linalg\__init__.py", line 73, in <module>
    from .linalg import *
  File "C:\Users\lib\site-packages\numpy\linalg\linalg.py", line 33, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden. 

Thank you for your help!
Lawa

**Comment by danielhrisca** [comment]
Hello @Lawa121 
It looks like a broken numpy installation

**Comment by JulienGrv** [comment]
It looks like there is an issue with your numpy installation. Try to reinstall asammdf: `pip install --force-reinstall asammdf`

**Comment by JulienGrv** [comment]
Or just reinstall numpy: `pip install --force-reinstall numpy`

**Comment by Lawa121** [comment]
This led to further problems but I was able to solve them by reinstalling PyQt5 and pyqtgraph as well.
Now it works. 
Thank you!!!
