### ISSUE TITLE
KeyError: 0 at to_dataframe()

### ISSUE THREAD

**Issue by morbult** [danielhrisca/asammdf#440]
Hi again Daniel,

I have a problem with some MDF 4.10 files while using to_dataframe()

python=3.7.9
asammdf=5.23.1
numpy=1.19.2

I run the following code

```py
import asammdf
mdf = asammdf.MDF('measurement.mf4')
df = mdf.to_dataframe()
```

and get the following error traceback

```
Traceback (most recent call last):

  File "<ipython-input-22-5eed72dd4ae1>", line 3, in <module>
    mdf.to_dataframe()

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 3441, in to_dataframe
    channels, raw=True, copy_master=False, validate=False,

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2414, in select
    channels=channels, minimal=False, skip_master=False

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7480, in included_channels
    result[master][master] = [self.masters_db[master]]

KeyError: 0
```

I will send you this example file by mail. 
It contains 3 groups and it seems it is the channels in group 0 that cause this error, because if I specify all channels except those in group 0, like so

```py
channels = [ch for ch, gi in mdf.channels_db.items() if gi[0][0] != 0]
df = mdf.to_dataframe(channels=channels)
```

it works as expected.

**Comment by danielhrisca** [comment]
Hello Mattias,

sorry for the delay. 

The problem was that the first channel group did not have a master channel. I've made a fix but I don't know how valid the data will be since for this channel group a virtual master will be generated using the index (so 18 samples => master = array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.])

**Comment by morbult** [comment]
I see. But it sounds like a reasonably thing to do to generate the master like that. It's very helpful just to be able to run ``to_dataframe`` without error. 

And in this case I am not using the channels in group 0. If I would be using any of those channels I would probably get the data in another way, like get or get_group.

**Comment by danielhrisca** [comment]
The implementation is like this, best effort.

**Comment by morbult** [comment]
Much appreciated!

**Comment by danielhrisca** [comment]
release 6.0.0 is available

**Comment by morbult** [comment]
Hi Daniel,

I have some new files which get this same KeyError: 0 when calling mdf.to_dataframe()
A common factor between these files is that they all have just one group with no master channel.
Using mdf.get works and it gives a dummy master array: [0, 1, 2, ...] which is fine and is what I would expect to get from mdf.to_dataframe.

I run asammdf 6.2.0

I will send you a scrambled file by email again, and here is the code and error

```py
mdf = asammdf.MDF('measurement_440_2.mdf')
mdf.to_dataframe()
```

```
Traceback (most recent call last):

  File "<ipython-input-39-760b3a9ce0a4>", line 1, in <module>
    mdf.to_dataframe()

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 3744, in to_dataframe
    channels, raw=True, copy_master=False, validate=False

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2657, in select
    channels=channels, minimal=False, skip_master=False

  File "C:\Users\mjosefs8\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\blocks\mdf_v3.py", line 3744, in included_channels
    gp_master = self.masters_db[group_index]

KeyError: 0
```
