### ISSUE TITLE
Error with exporting mf4 file

### ISSUE THREAD

**Issue by Qutadah** [danielhrisca/asammdf#445]
Hello,

i am recieving this error when importing a specific DBC file and exporting the mf4 file, how can I solve this?

Thanks !

here is the Error:

Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 307, in run
  File "asammdf\mdf.py", line 3788, in extract_can_logging
  File "asammdf\blocks\bus_logging_utils.py", line 281, in extract_mux
  File "<__array_function__ internals>", line 6, in isclose
  File "numpy\core\numeric.py", line 2287, in isclose
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Details: 2020-11-27, 09:30:52
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 307, in run
  File "asammdf\mdf.py", line 3788, in extract_can_logging
  File "asammdf\blocks\bus_logging_utils.py", line 281, in extract_mux
  File "<__array_function__ internals>", line 6, in isclose
  File "numpy\core\numeric.py", line 2287, in isclose
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\file.py", line 1319, in extract_can_logging
  File "asammdf\gui\utils.py", line 272, in run_thread_with_progress

**Comment by danielhrisca** [comment]
Can you try the development branch code?

**Comment by Qutadah** [comment]
how do I do this ? Im pretty new to this and I have downloaded the gui, how do I download the fixed one?

**Comment by danielhrisca** [comment]
> I have downloaded the gui

do you mean the procompiled .exe?

**Comment by Qutadah** [comment]
I downloaded the code from the development branch.. whats to do next? Thanks,

**Comment by Qutadah** [comment]
yes exactly the .exe

**Comment by danielhrisca** [comment]
you need python and the necessary dependencies to run from source
```
python -m pip install asammdf[gui]
python -m pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip
```

**Comment by Qutadah** [comment]
I cant download python due to company security reasons, so im using google colab.... any idea how this can be done there? I ran the code there and it says as follows:

Successfully installed asammdf-6.0.0.dev24

where would this be installed?

**Comment by danielhrisca** [comment]
try this :
```python
from asammdf.gui.asammdfgui import main
main()
```

**Comment by Qutadah** [comment]
xlsx is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/canmatrix/formats/xlsx.py", line 32, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
usage: ipykernel_launcher.py [-h]
                             [--measurements [MEASUREMENTS [MEASUREMENTS ...]]]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-d8ca9721-19b6-4cfb-8372-ee917701edd3.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by Qutadah** [comment]
installed asammdf and theres still an error

usage: ipykernel_launcher.py [-h]
                             [--measurements [MEASUREMENTS [MEASUREMENTS ...]]]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-d8ca9721-19b6-4cfb-8372-ee917701edd3.json
An exception has occurred, use %tb to see the full traceback.

**Comment by danielhrisca** [comment]
```
python -m pip install xlrd xlwt xlsxwriter lxml pyaml
```

**Comment by Qutadah** [comment]
usage: ipykernel_launcher.py [-h]
                             [--measurements [MEASUREMENTS [MEASUREMENTS ...]]]
ipykernel_launcher.py: error: unrecognized arguments: -f /root/.local/share/jupyter/runtime/kernel-d8ca9721-19b6-4cfb-8372-ee917701edd3.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by danielhrisca** [comment]
Using the ipython console makes things wird, please try this

```python
import sys
from PyQt5 import QtWidgets

from asammdf.gui.utils import excepthook
from asammdf.gui.widgets.main import MainWindow

app = QtWidgets.QApplication()
app.setOrganizationName("py-asammdf")
app.setOrganizationDomain("py-asammdf")
app.setApplicationName("py-asammdf")
main = MainWindow()

app.setStyle(QtWidgets.QStyleFactory.create("Fusion"))
app.exec_()
```

**Comment by Qutadah** [comment]
Its ok, i worked with cmd and used private laptop, but cmd keeps running in background wheni run it, how do i remove it?

Thanks alot!

**Comment by Qutadah** [comment]
Hi, i tried again with arxml file, it works, but there is one .dbc database giving this error when extracted.

`2020-11-30, 22:03:06
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asammdf\gui\utils.py", line 301, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asammdf\mdf.py", line 3800, in extract_can_logging
    extracted_signals = extract_mux(
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asammdf\blocks\bus_logging_utils.py", line 306, in extract_mux
    "invalidation_bits": np.isclose(samples, max_val),
  File "<__array_function__ internals>", line 5, in isclose
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\numeric.py", line 2257, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

--------------------------------------------------------------------------------
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asammdf\gui\widgets\file.py", line 1305, in extract_can_logging
    mdf = run_thread_with_progress(
  File "C:\Users\Qutadah Rababah\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asammdf\gui\utils.py", line 266, in run_thread_with_progress
    raise Exception(thr.error)
`

any idea?

**Comment by danielhrisca** [comment]
Menu - > Settings - > ignore value2text conversions

Does this make a difference?

**Comment by Qutadah** [comment]
I am still recieving following error:

2020-12-01, 11:14:58
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 307, in run
  File "asammdf\mdf.py", line 3788, in extract_can_logging
  File "asammdf\blocks\bus_logging_utils.py", line 281, in extract_mux
  File "<__array_function__ internals>", line 6, in isclose
  File "numpy\core\numeric.py", line 2287, in isclose
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\file.py", line 1319, in extract_can_logging
  File "asammdf\gui\utils.py", line 272, in run_thread_with_progress

**Comment by danielhrisca** [comment]
@Qutadah you can try the exe builds https://ci.appveyor.com/project/danielhrisca/asammdf/build/artifacts

**Comment by Qutadah** [comment]
@danielhrisca Thank you for the execution builds, I am still receiving this error with this one dbc file,

2020-12-02, 14:37:33
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 301, in run
  File "asammdf\mdf.py", line 3834, in extract_can_logging
  File "asammdf\blocks\bus_logging_utils.py", line 307, in extract_mux
  File "<__array_function__ internals>", line 6, in isclose
  File "numpy\core\numeric.py", line 2287, in isclose
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\file.py", line 1311, in extract_can_logging
  File "asammdf\gui\utils.py", line 266, in run_thread_with_progress

_____
One more question:

How are arxml files in the gui read? are they converted first to dbc and then read? or directly read as arxml? because we are considering the possibility that there is somewhat a conversion factor or if the values will differ in the analysis of mf4 files with arxml as in with dbc converted from arxml... I saw both mf4 files extracted once with arxml and once with converted dbc they are the same... So I was wondering if the GUI does it the same way or not. cause if not then I believe no Infos are getting lost from conversion to dbc from arxml... which I am really interested to know.

Thanks!

**Comment by danielhrisca** [comment]
> How are arxml files in the gui read?

We use the canmatrix library to load arxml and dbc files. There is no conversion done, the database files are directly parsed 

Is there any way you could send the mf4 and arxml files for analysis?

**Comment by Qutadah** [comment]
Hallo Daniel,

I have sent you an email. Thanks

**Comment by danielhrisca** [comment]
@Qutadah me too :) please check the fix

**Comment by Qutadah** [comment]
@danielhrisca  Thank you, works perfect 👍🏼
