### ISSUE TITLE
import module reported an error

### ISSUE THREAD

**Issue by Yuanli-Liu** [danielhrisca/asammdf#450]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```
Output
```
'python=3.8.6 (default, Nov 18 2020, 13:49:49) \n[GCC 8.3.0]'
'os=Linux-5.4.0-56-generic-x86_64-with-glibc2.2.5'
'numpy=1.19.4'
xls is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/xls.py", line 34, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'
xlsx is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/xlsx.py", line 32, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
yaml is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/yaml.py", line 32, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
'python=3.8.6 (default, Nov 18 2020, 13:49:49) \n[GCC 8.3.0]'
'os=Linux-5.4.0-56-generic-x86_64-with-glibc2.2.5'
'numpy=1.19.4'
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    import asammdf
  File "/usr/local/lib/python3.8/site-packages/asammdf/__init__.py", line 14, in <module>
    from .blocks.mdf_v2 import MDF2
  File "/usr/local/lib/python3.8/site-packages/asammdf/blocks/mdf_v2.py", line 4, in <module>
    from .mdf_v3 import MDF3
  File "/usr/local/lib/python3.8/site-packages/asammdf/blocks/mdf_v3.py", line 37, in <module>
    from ..signal import Signal
  File "/usr/local/lib/python3.8/site-packages/asammdf/signal.py", line 10, in <module>
    from .blocks import v2_v3_blocks as v3b
  File "/usr/local/lib/python3.8/site-packages/asammdf/blocks/v2_v3_blocks.py", line 17, in <module>
    from .utils import get_fields, get_text_v3, MdfException, UINT16_u, UINT16_uf
  File "/usr/local/lib/python3.8/site-packages/asammdf/blocks/utils.py", line 46, in <module>
    from canmatrix.arxml import load as arxml_load
  File "/usr/local/lib/python3.8/site-packages/canmatrix/__init__.py", line 11, in <module>
    from canmatrix.canmatrix import (
  File "/usr/local/lib/python3.8/site-packages/canmatrix/canmatrix.py", line 42, in <module>
    from future.moves.itertools import zip_longest
  File "/usr/local/lib/python3.8/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/usr/local/lib/python3.8/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/usr/local/lib/python3.8/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/code/LogSim/sdk/test.py", line 16, in <module>
    pprint("asammdf=" + asammdf.__version__)
AttributeError: partially initialized module 'asammdf' has no attribute '__version__' (most likely due to a circular import)
```

# Description
the version of asammdf is `6.0.1`

**Comment by danielhrisca** [comment]
I can't reproduce this error. 

Can you move `test.py` to another path and run it from there? (like `/home/<user>` for example)

**Comment by JulienGrv** [comment]
The import errors are due to canmatrix. Install the missing modules: `pip install xlrd XlsxWriter PyYAML`

**Comment by Yuanli-Liu** [comment]
> I can't reproduce this error.
> 
> Can you move `test.py` to another path and run it from there? (like `/home/<user>` for example)

I run this in a docker container.
## Docker file
```
FROM python:3.8
RUN pip install -r requirements.txt
```
## requirements.txt
```
asammdf==6.0.1
```

**Comment by Yuanli-Liu** [comment]
Although it reports error, it still works normally
```
root@root:/# python
Python 3.8.6 (default, Nov 18 2020, 13:49:49) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asammdf
xls is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/xls.py", line 34, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'
xlsx is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/xlsx.py", line 32, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
yaml is not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/canmatrix/formats/yaml.py", line 32, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
>>> asammdf.__version__
'6.0.1'
```

**Comment by Yuanli-Liu** [comment]
> The import errors are due to canmatrix. Install the missing modules: `pip install xlrd XlsxWriter PyYAML`

it works. Thanks!!
