### ISSUE TITLE
Segfault when decoding SAE J1979 data from CSS Electronics

### ISSUE THREAD

**Issue by rfrowe** [danielhrisca/asammdf#475]
# Python version
```python
'python=3.8.7 (default, Jan 12 2021, 17:16:32) \n[GCC 8.3.0]'
'os=Linux-4.19.121-linuxkit-x86_64-with-glibc2.2.5'
'numpy=1.19.5'
xls is not supported
xlsx is not supported
'asammdf=6.1.2'
```

Specifically, this is inside the `python:3.8-slim` docker container.

# Code 

  ## MDF version
  4.11

  ## Code snippet
```python
from canmatrix.formats.dbc import load as load_dbc
from asammdf import MDF4

with open('CSS-Electronics-OBD2-v1.4.dbc', 'rb') as f:
    dbc = load_dbc(f, dbcImportEncoding='utf-8')
data = MDF4('31CB1F25_00000022_00000002.mf4')

sig = data.get_can_signal('S1_PID_05_EngineCoolantTemp', database=dbc)
print(sig)
```
  
  ## Traceback
```
Segmentation fault
```

When run under gdb, I see:
```
(gdb) bt
#0  0x00007f6349e61720 in ?? () from /usr/local/lib/python3.8/site-packages/asammdf/blocks/cutils.cpython-38-x86_64-linux-gnu.so
#1  0x00007f634b68f523 in PyCFunction_Call () from /usr/local/lib/libpython3.8.so.1.0
#2  0x00007f634b68e2e4 in _PyObject_MakeTpCall () from /usr/local/lib/libpython3.8.so.1.0
#3  0x00007f634b70cf27 in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.8.so.1.0
#4  0x00007f634b7079f1 in _PyEval_EvalCodeWithName () from /usr/local/lib/libpython3.8.so.1.0
#5  0x00007f634b68eb42 in _PyFunction_Vectorcall () from /usr/local/lib/libpython3.8.so.1.0
#6  0x00007f634b690d99 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#7  0x00007f634b7098a2 in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.8.so.1.0
#8  0x00007f634b7079f1 in _PyEval_EvalCodeWithName () from /usr/local/lib/libpython3.8.so.1.0
#9  0x00007f634b68eb42 in _PyFunction_Vectorcall () from /usr/local/lib/libpython3.8.so.1.0
#10 0x00007f634b690d99 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#11 0x00007f634b7098a2 in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.8.so.1.0
#12 0x00007f634b7079f1 in _PyEval_EvalCodeWithName () from /usr/local/lib/libpython3.8.so.1.0
#13 0x00007f634b68eb42 in _PyFunction_Vectorcall () from /usr/local/lib/libpython3.8.so.1.0
#14 0x00007f634b690d99 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#15 0x00007f634b7098a2 in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.8.so.1.0
#16 0x00007f634b7079f1 in _PyEval_EvalCodeWithName () from /usr/local/lib/libpython3.8.so.1.0
#17 0x00007f634b7076f9 in PyEval_EvalCodeEx () from /usr/local/lib/libpython3.8.so.1.0
#18 0x00007f634b7076bb in PyEval_EvalCode () from /usr/local/lib/libpython3.8.so.1.0
#19 0x00007f634b791aea in ?? () from /usr/local/lib/libpython3.8.so.1.0
#20 0x00007f634b791a82 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#21 0x00007f634b648443 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#22 0x00007f634b64822c in PyRun_SimpleFileExFlags () from /usr/local/lib/libpython3.8.so.1.0
#23 0x00007f634b65410a in ?? () from /usr/local/lib/libpython3.8.so.1.0
#24 0x00007f634b797929 in Py_BytesMain () from /usr/local/lib/libpython3.8.so.1.0
#25 0x00007f634b1df09b in __libc_start_main (main=0x5652b1d86050 <main>, argc=2, argv=0x7ffe231fd808, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe231fd7f8) at ../csu/libc-start.c:308
#26 0x00005652b1d8608a in _start ()
```
  
# Description
The data needed for reproduction is provided for free by [CSS Electronics](https://canlogger1000.csselectronics.com/files/guides/mdf-intro/OBD2-DBC-MDF4.zip). Unzip the downloaded archive and enter the newly created `OBD2-DBC-MDF4` directory. Then, paste the reproduction script in `repro.py`. Either execute this script or do so via docker:
```
$ docker run -it --entrypoint bash -v `pwd`:/ws python:3.8-slim
# apt update && apt install -y gcc gdb
# pip install asammdf
# cd ws
# python repro.py
# gdb python
(gdb) run repro.py
```

When the same script is run on macOS 10.15.6, the issue does not occur and `sig` is successfully extracted. In this case, it was run with:
```
('python=3.8.5 (default, Jul 21 2020, 10:48:26) \n'
 '[Clang 11.0.3 (clang-1103.0.32.62)]')
'os=macOS-10.15.6-x86_64-i386-64bit'
'numpy=1.19.5'
xls is not supported
xlsx is not supported
'asammdf=6.1.2'
```

**Comment by rfrowe** [comment]
@danielhrisca I'm closing this as a duplicate of #472. Although, this should be a good repro case for you since the author of that issue hasn't provided their MDF data to you. I installing development asammdf and the gdb backtrace looks the same.

**Comment by danielhrisca** [comment]
Ok I'll try to verify tomorrow
