### ISSUE TITLE
whereis() is giving is giving KeyError when signal is not present in the file

### ISSUE THREAD

**Issue by vaasu070** [danielhrisca/asammdf#479]
Hi , `whereis()` function is giving error when called with non existent signal. 

I just updated `asammdf `library from version 5.20.6 to latest 6.1.2. I did not observe this behavior in version 5.20.6

```
from asammdf import MDF

filePath = "C:/Users/vaasu/Desktop/Data/Recorder_2020-06-05_10-22_0120.MF4"

data = MDF(filePath)

signals = ['A2', "YawRate"]
pos = data.whereis("sds")
print(pos)

Traceback (most recent call last):
  File "c:/Users/vaasu/Desktop/xray-github/x-ray/prac.py", line 9, in <module>
    pos = data.whereis("sds")
  File "C:\Users\vaasu\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 4493, in whereis
    self.channels_db[channel], source_name=source_name, source_path=source_path
KeyError: 'sds'
```

It also throws following error when there are multiple occurrences of the same signal when `whereis()` and `to_dataframe()` is called.

```
asammdf - ERROR - Multiple occurances for channel "A2": ((2, 1), (246, 1)). Provide both "group" and "index" arguments to select another data group
NoneType: None
Traceback (most recent call last):
  File "c:/Users/vaasu/Desktop/xray-github/x-ray/prac.py", line 10, in <module>
    df = data.to_dataframe(channels=signals)
  File "C:\Users\vaasu\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 3475, in to_dataframe
    mdf = self.filter(channels)
  File "C:\Users\vaasu\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 1464, in filter
    gps = self.included_channels(channels=channels)
  File "C:\Users\vaasu\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7411, in included_channels
    group, idx = self._validate_channel_selection(name)
  File "C:\Users\vaasu\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_common.py", line 131, in _validate_channel_selection
    raise MdfException(message)
asammdf.blocks.utils.MdfException: Multiple occurances for channel "A2": ((2, 1), (246, 1)). Provide both "group" and "index" arguments to select another data group
```

**Comment by danielhrisca** [comment]
with the code in the development branch the method `where_is` should not raise an error.

Regarding the other problem, the behavior has changed since [release 6.0.0](https://github.com/danielhrisca/asammdf/releases/tag/6.0.0)

**Comment by vaasu070** [comment]
Hi again, 
In `to_dataframe`, when there are multiple occurrences of a signal , it asks me to specify group and index arguments.
But according to documentation [here](https://asammdf.readthedocs.io/en/latest/api.html), it does not take those arguments.

**Comment by JulienGrv** [comment]
The documentation of `to_dataframe` is missing some details regarding the options `channels`but its usage is the same as the function `filter`

**Comment by danielhrisca** [comment]
@vaasu070 I've updated the documentation, I hope it is clear now https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF.to_dataframe
