### ISSUE TITLE
Exception by open Unsorted.MF4 file

### ISSUE THREAD

**Issue by EbATpy** [danielhrisca/asammdf#488]
asammdf 6.0.0

Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\utils.py", line 301, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\mdf.py", line 134, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 390, in __init__
    self._read(mapped=True)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 765, in _read
    self._sort()
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9547, in _sort
    new_data = decompress(new_data, 0, dtblock_raw_size)
zlib.error: Error -3 while decompressing data: incorrect header check

Details: 2021-02-15, 15:43:44
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\utils.py", line 301, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\mdf.py", line 134, in __init__
    self._mdf = MDF4(name, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 390, in __init__
    self._read(mapped=True)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 765, in _read
    self._sort()
  File "C:\Program Files\Python37\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9547, in _sort
    new_data = decompress(new_data, 0, dtblock_raw_size)
zlib.error: Error -3 while decompressing data: incorrect header check

--------------------------------------------------------------------------------
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\widgets\main.py", line 849, in open
    self.open_file(event)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\widgets\main.py", line 890, in open_file
    self._open_file(file_name)
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\widgets\main.py", line 865, in _open_file
    self,
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\widgets\file.py", line 153, in __init__
    progress=progress,
  File "C:\Program Files\Python37\lib\site-packages\asammdf\gui\utils.py", line 266, in run_thread_with_progress
    raise Exception(thr.error)

**Comment by danielhrisca** [comment]
I think this is already fixed in 6.2.0

**Comment by EbATpy** [comment]
Version  asammdf 6.2.0 issues by opening folder with mf4 files!
see [download this file](https://github.com/danielhrisca/asammdf/files/5982194/Examples.zip)
Files:
Vector_SingleDZ_Unsorted.mf4
dSPACE_HILAPITimeout.mf4
dSPACE_HILAPITrigger.mf4
...

**Comment by danielhrisca** [comment]
I don't think you are allowed to share those files

**Comment by danielhrisca** [comment]
> Version asammdf 6.2.0 issues by opening folder with mf4 files!

Indeed there is some problem with the unsorted files. I will investigate

**Comment by EbATpy** [comment]
ok please delite the files, or this issue item.

**Comment by EbATpy** [comment]
perfect
