### ISSUE TITLE
DBC Factors and Offsets not applied

### ISSUE THREAD

**Issue by LaurentBerder** [danielhrisca/asammdf#512]
Hi,

I have a DBC file that specifies factor and offset for some of the signals (see below):

> BO_ 2461270016 _STU_BATTERY_SOC: 8 Vector__XXX
>  SG_ _STU_EV_SOC : 24|16@1+ (0.0278,0) [0|0] "%" Vector__XXX
![DBC](https://user-images.githubusercontent.com/19341543/117445753-5f325f00-af3b-11eb-9001-0d33933dfe31.png)

When I extract bus logging using this DBC, I get the right channels, but factors and offsets are not applied at all.

Here, I see the battery state of charge (which can only be between 0 and 100%) as read by extract_bus_logging:
![battery_soc_raw](https://user-images.githubusercontent.com/19341543/117445698-4a55cb80-af3b-11eb-85ca-1d504798a8fb.png)

And here, we can see what the correct battery state of charge should be (I just needed to multiply the channel by the factor of 0.0278):
![battery_soc_correct](https://user-images.githubusercontent.com/19341543/117445794-6ce7e480-af3b-11eb-92e1-35de4f3f724a.png)

How could I **automatically** detect and apply factors and offsets?

  ## Code snippet
`dbc = {"CAN": dbc_files}`
`mdf = MDF.concatenate(mf4_files)`
`mdf_scaled = mdf.extract_bus_logging(dbc, ignore_invalid_signals=True)`
  
  ## Python version
('python=3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.19.4'
'asammdf=6.1.2'

  ## MDF version
4.11

**Comment by danielhrisca** [comment]
@LaurentBerder can you check with the development branch code?

**Comment by LaurentBerder** [comment]
> @LaurentBerder can you check with the development branch code?

I installed version 6.0.0.dev12.

I noticed that `extract_bus_logging` was changed to `extract_can_logging`, so I changed my code appropriately.
However, this does not have any result anymore:
```python
dbc = {"CAN": dbc_files}
mdf = MDF.concatenate(mf4_files)
mdf_scaled = mdf.extract_can_logging(dbc)
print([c.name for c in mdf_scaled.iter_channels()])
```
This returns an empty list `[]`.

What else should I change in my code to get the signals indicated by the DBC file?

**Comment by danielhrisca** [comment]
> I installed version 6.0.0.dev12.

the latest development version is 6.3.0.dev29

**Comment by LaurentBerder** [comment]
Sorry, I'd just installed the latest available branch in pip.
So I'm now running 6.3.0.dev29.

And the error I now get when running `mdf_scaled = mdf.extract_bus_logging(dbc, ignore_invalid_signals=True)` is
```python
Traceback (most recent call last):
  File "G:\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-41-9d52c008900e>", line 1, in <module>
    mdf_scaled = mdf.extract_bus_logging(database_files=dbc, ignore_invalid_signals=True)
  File "G:\venv\lib\site-packages\asammdf\mdf.py", line 4033, in extract_bus_logging
    out = self._extract_can_logging(
  File "G:\venv\lib\site-packages\asammdf\mdf.py", line 4069, in _extract_can_logging
    for (dbc_name, bus_channel) in dbc_files:
TypeError: cannot unpack non-iterable WindowsPath object
```

**Comment by danielhrisca** [comment]
The databases dict has a new structure now (see https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.extract_bus_logging)

**Comment by LaurentBerder** [comment]
Oh, I see!
So I need to change `dbc = {"CAN": dbc_files}` to `dbc = {"CAN": [(f, 0) for f in dbc_files]}`

Now the whole thing is running smoothly, but the factor is still not applied.
Here's what I can see for the SOC of that file:
![image](https://user-images.githubusercontent.com/19341543/118832146-a9fb9180-b8c0-11eb-9d00-c54ac5e12e65.png)
While it should in fact be the following:
![image](https://user-images.githubusercontent.com/19341543/118832310-cef00480-b8c0-11eb-9ced-2c402b505d8a.png)

As mentionned above, the factor of 0.0278 is specified in the dbc file:
```
BO_ 2461270016 _STU_BATTERY_SOC: 8 Vector__XXX
 SG_ _STU_EV_SOC : 24|16@1+ (0.0278,0) [0|0] "%" Vector__XXX
```

**Comment by danielhrisca** [comment]
@LaurentBerder I cannot replicate the behavior on my side. Could you send your input files for analysis?

**Comment by LaurentBerder** [comment]
@danielhrisca you'll find a reproducible example on [this link](https://www.dropbox.com/s/nvlpisqtf0cu10o/asammdf%20factor.zip?dl=0), with input file, dbc file and code.

**Comment by danielhrisca** [comment]
the signals is decoded by it looks like the factor is not correct

The raw signal values (uint16 from the CAN payload) are:

```
[35612 35612 35612 35612 35612 35612 35612 35612 35612 35612 35612 35612
 35612 35612 35612 35612 35608 35608 35608 35608 35608 35608 35604 35604
 35604 35604 35604 35604 35604 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35600 35604 35604 35604 35604 35604 35604 35604
 35604 35604 35604 35604 35600 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600 35600
 35600 35600 35600 35600 35596 35596 35596 35596 35596 35596 35596 35588
 35588 35588 35588 35588 35588 35588 35588 35588 35588 35588 35588 35588
 35588 35588 35588 35588 35588 35596 35596 35596 35596 35596 35596 35596
 35596 35596 35596 35596 35596 35596 35596 35596 35596 35596 35596 35596
 35596 35588 35588 35588 35588 35588 35588 35588 35588 35588 35584 35584
 35584 35584 35584 35584 35584 35584 35584 35584 35584 35580 35580 35580
 35580 35580 35580 35580 35580 35580 35580 35580 35580 35580 35576 35576
 35576 35576 35576 35576 35576 35576 35576 35576 35576 35576 35576 35576] 
```

Then the factor of 0.028 is applied and the decoded values are 

```
[990.0136 990.0136 990.0136 990.0136 990.0136 990.0136 990.0136 990.0136
 990.0136 990.0136 990.0136 990.0136 990.0136 990.0136 990.0136 990.0136
 989.9024 989.9024 989.9024 989.9024 989.9024 989.9024 989.7912 989.7912
 989.7912 989.7912 989.7912 989.7912 989.7912 989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.7912 989.7912 989.7912 989.7912 989.7912 989.7912 989.7912
 989.7912 989.7912 989.7912 989.7912 989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.68   989.68   989.68   989.68   989.68   989.68   989.68   989.68
 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688 989.3464
 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464
 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464
 989.3464 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688
 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688 989.5688
 989.5688 989.5688 989.5688 989.5688 989.5688 989.3464 989.3464 989.3464
 989.3464 989.3464 989.3464 989.3464 989.3464 989.3464 989.2352 989.2352
 989.2352 989.2352 989.2352 989.2352 989.2352 989.2352 989.2352 989.2352
 989.2352 989.124  989.124  989.124  989.124  989.124  989.124  989.124
 989.124  989.124  989.124  989.124  989.124  989.124  989.0128 989.0128
 989.0128 989.0128 989.0128 989.0128 989.0128 989.0128 989.0128 989.0128
 989.0128 989.0128 989.0128 989.0128]
```

If you once again apply the factor of 0.0028 you get what you expected the signal to be

```
[27.52237808 27.52237808 27.52237808 27.52237808 27.52237808 27.52237808
 27.52237808 27.52237808 27.52237808 27.52237808 27.52237808 27.52237808
 27.52237808 27.52237808 27.52237808 27.52237808 27.51928672 27.51928672
 27.51928672 27.51928672 27.51928672 27.51928672 27.51619536 27.51619536
 27.51619536 27.51619536 27.51619536 27.51619536 27.51619536 27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.51619536
 27.51619536 27.51619536 27.51619536 27.51619536 27.51619536 27.51619536
 27.51619536 27.51619536 27.51619536 27.51619536 27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.513104   27.513104
 27.513104   27.513104   27.513104   27.513104   27.51001264 27.51001264
 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264 27.50382992
 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992
 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992
 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992 27.51001264
 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264
 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264
 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264 27.51001264
 27.51001264 27.50382992 27.50382992 27.50382992 27.50382992 27.50382992
 27.50382992 27.50382992 27.50382992 27.50382992 27.50073856 27.50073856
 27.50073856 27.50073856 27.50073856 27.50073856 27.50073856 27.50073856
 27.50073856 27.50073856 27.50073856 27.4976472  27.4976472  27.4976472
 27.4976472  27.4976472  27.4976472  27.4976472  27.4976472  27.4976472
 27.4976472  27.4976472  27.4976472  27.4976472  27.49455584 27.49455584
 27.49455584 27.49455584 27.49455584 27.49455584 27.49455584 27.49455584
 27.49455584 27.49455584 27.49455584 27.49455584 27.49455584 27.49455584]
```

**Comment by LaurentBerder** [comment]
Oh, it does, I see!
Thanks a lot for your help, sorry for the bother.
