### ISSUE TITLE
Change: DBC-decoded Channel Groups split by CAN ID (not J1939 PGN)

### ISSUE THREAD

**Issue by MatinF** [danielhrisca/asammdf#517]
**Challenge**

In many dataset, we have _multiple 29-bit CAN IDs that map to the same 18-bit PGNs_. The result currently in asammdf is that the DBC-decoded signal outputs become "combined" across multiple CAN IDs, which is not the intention and results in weird plots (see below).

**Suggestion**

I think an ideal way to solve both of the above would be to adjust the logic of how channel groups are created in asammdf. Instead of forming them purely based on the CAN ID or PGN, the channel groups would generally be formed as follows:

`Channel group X ([Bus Channel]: [CAN_ID] [Message_Name])`

Example:

Today, the decoding would produce the following:

`Channel group 0 (0x1F112 VesselHeading)`

While the new method for the same dataset could produce the following:

```
Channel group 0 (1: 0x9F11202 VesselHeading)
Channel group 1 (2: 0x9F11202 VesselHeading)
Channel group 2 (1: 0x9F11223 VesselHeading)
```

So essentially, instead of grouping by e.g. PGN alone, you would group based on the full 29 bit CAN ID _and_ the bus channel. 

Note that the aim is not to change the J1939 PGN matching logic - i.e. the lookup in a J1939 DBC should still happen based on the 18-bit PGN being matched, not the full 29-bit CAN ID. However, the point is that when multiple separate CAN IDs match the same PGN, they should be split into separate channel groups - rather than bundled.

I believe the above change would generally produce the intended result, and you'd avoid plots like the below:
![image](https://user-images.githubusercontent.com/26184427/115137213-056a0380-a025-11eb-8e48-d735f4268069.png)

![image](https://user-images.githubusercontent.com/26184427/118864629-7466a080-b8e0-11eb-94fb-85a5e30d284e.png)

Let me know your thoughts :-)

**Comment by MatinF** [comment]
Thanks Daniel, this seems like a good solution!

Quick comments:

1) I would suggest having it disabled by default in the GUI (as I think the preference for PGN consolidation will be a rare exception)

2) I tried it just now, but received below error when I tried to disable it and run the decoding. The error also comes if enabling it:

```
Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 381, in run
    self.output = self._target(*self._args, **self._kwargs)
TypeError: extract_bus_logging() got an unexpected keyword argument 'consolidate_j1939'


Details: 2021-05-20, 09:25:34
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 381, in run
    self.output = self._target(*self._args, **self._kwargs)
TypeError: extract_bus_logging() got an unexpected keyword argument 'consolidate_j1939'

--------------------------------------------------------------------------------
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\widgets\file.py", line 1506, in extract_bus_logging
    progress=progress,
  File "c:\users\marti\appdata\local\programs\python\python37\lib\site-packages\asammdf\gui\utils.py", line 346, in run_thread_with_progress
    raise Exception(thr.error)

```

**Comment by MatinF** [comment]
Great, it seems to work now! 

Two minor comments:

1) I would suggest making the consolidation off by default as mentioned above

2) If it's possible to add the full CAN ID in the Channel Group name, that would be ideal. This would allow for distinguishing between the channel groups directly, as opposed to the picture below. I think it's nice to also have the PGN available, but if you think both become "too much" to have in parallel, maybe the PGN could be visible when double clicking a channel group (while the CAN ID is directly visible in the channel group name)

![image](https://user-images.githubusercontent.com/26184427/118942613-30f94a00-b953-11eb-8e9d-44767f1a4d89.png)

**Comment by MatinF** [comment]
I think the latest dev branch solves this nicely!
