### ISSUE TITLE
ValueError: To change to a dtype of a different size, the array must be C-contiguous

### ISSUE THREAD

**Issue by deneskr1s0f** [danielhrisca/asammdf#520]
Hello All,

I have a problem, which is I trying to open a mf4 file with asammdf, but it says that:

Traceback (most recent call last):
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\mdf.py", line 204, in __init__
    self._mdf = MDF4(name, channels=channels, **kwargs)
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 403, in __init__
    self._read(mapped=True)
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 788, in _read
    self._process_bus_logging()
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 9960, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 10098, in _process_can_logging
    samples_only=True,
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6190, in get
    master_is_required=master_is_required,
  File "C:\TCC\Tools\python3\3.7.4-26_WIN64\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6973, in _get_scalar
    vals = vals.view(channel_dtype)
ValueError: To change to a dtype of a different size, the array must be C-contiguous

I tried out, to the measurement file won't be sorted,  but the Error was the same.

I use 6.2.0 version of asammdf, and 3.7.0 python version

Any of you ever met this problem?

Is there any suggestion how can I deal with this kind of problem?

Thank in advance

**Comment by danielhrisca** [comment]
@deneskr1s0f please try the latest development branch code (v6.3.0.dev35)

**Comment by vaasu070** [comment]
I tried development branch `asammdf-6.3.0.dev46`. It did solve the above error, however It is throwing below new error 

## Traceback
```
  File ".\prac.py", line 7, in <module>
    data = MDF(file)
  File "C:\Users\vaasu\.virtualenvs\XRay-Hw8tVa3y\lib\site-packages\asammdf\mdf.py", line 232, in __init__
    self._mdf = MDF4(name, channels=channels, **kwargs)
  File "C:\Users\vaasu\.virtualenvs\XRay-Hw8tVa3y\lib\site-packages\asammdf\blocks\mdf_v4.py", line 415, in __init__
    self._read(mapped=True)
  File "C:\Users\vaasu\.virtualenvs\XRay-Hw8tVa3y\lib\site-packages\asammdf\blocks\mdf_v4.py", line 805, in _read
    self._process_bus_logging()
  File "C:\Users\vaasu\.virtualenvs\XRay-Hw8tVa3y\lib\site-packages\asammdf\blocks\mdf_v4.py", line 10193, in _process_bus_logging
    self._process_can_logging(index, group)
  File "C:\Users\vaasu\.virtualenvs\XRay-Hw8tVa3y\lib\site-packages\asammdf\blocks\mdf_v4.py", line 10346, in _process_can_logging
    bus_data_bytes = data_bytes[idx_]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 4296 but corresponding boolean dimension is 537
```

**Comment by danielhrisca** [comment]
@vaasu070 any chance you can send a scrambled file?

**Comment by vaasu070** [comment]
> @vaasu070 any chance you can send a scrambled file?

@danielhrisca  Sorry I cannot share it because of company policy
