### ISSUE TITLE
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMainWindow'

### ISSUE THREAD

**Issue by axtschmied** [danielhrisca/asammdf#537]
# Python version
('python=3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.21.0'
’asammdf=6.2.0’
  
# Traceback
```
Traceback (most recent call last):
  File "c:\kbapps\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\kbapps\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\KBApps\Python39\Scripts\asammdf.exe\__main__.py", line 4, in <module>
  File "c:\kbapps\python39\lib\site-packages\asammdf\__init__.py", line 18, in <module>
    from .gui import plot
  File "c:\kbapps\python39\lib\site-packages\asammdf\gui\plot.py", line 9, in <module>
    from .widgets.plot_standalone import PlotWindow
  File "c:\kbapps\python39\lib\site-packages\asammdf\gui\widgets\plot_standalone.py", line 10, in <module>
    from .plot import Plot
  File "c:\kbapps\python39\lib\site-packages\asammdf\gui\widgets\plot.py", line 22, in <module>
    from .dict_to_tree import ComputedChannelInfoWindow
  File "c:\kbapps\python39\lib\site-packages\asammdf\gui\widgets\dict_to_tree.py", line 38, in <module>
    class ComputedChannelInfoWindow(QtGui.QMainWindow):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMainWindow'
```
  
# Description
Hello,
I get the error message above when trying to start the asammdf GUI or just to import asammdf in Python. This is probably not an issue with asammdf, but with my setup, but I would need some help, because I have no idea how to solve this. I experienced the same with Python 3.8 and 3.9, asammdf version 6.2.0 and the head of the development branch, different PyQt5 versions...

The computer that I am experiencing this on, is freshly installed. asammdf is working properly on another computer with basically the same package versions.

I would be very grateful, if somebody could help me solve this.

## pip freeze
```
asammdf==6.2.0
attrs==21.2.0
bitstruct==8.11.1
canmatrix==0.9.3
click==8.0.1
colorama==0.4.4
cycler==0.10.0
future==0.18.2
kiwisolver==1.3.1
lxml==4.6.3
lz4==3.1.3
matplotlib==3.4.2
natsort==7.1.1
numexpr==2.7.3
numpy==1.21.0
pandas==1.3.0
pathlib2==2.3.6
Pillow==8.3.1
psutil==5.8.0
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqtgraph==0.12.2
python-dateutil==2.8.2
pytz==2021.1
six==1.16.0
```

**Comment by danielhrisca** [comment]
Thanks @axtschmied I've made the fix

**Comment by axtschmied** [comment]
Hello Daniel,
thank you for fixing it so quickly. In the meantime I realized that I only get this error if I have pyqtgraph 0.12 installed. If I install version 0.11.1 instead, asammdf works.
