### ISSUE TITLE
Different tries of file conversion from 4.1 to 3.x with errors

### ISSUE THREAD

**Issue by s9mahueb** [danielhrisca/asammdf#545]
# Python version
```python
('python=3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.20.2'
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=6.3.0.dev47'
```
# Code 

  ## MDF version
4.1

  ## Code snippet 1
```python
#coding: latin-1 
from asammdf import MDF, Signal
import asammdf
 
compressionVal = 1
newVersion = "3.30"
obj = MDF(r"C:\File.mf4")
obj2 = MDF(version = newVersion)
for Signal in obj:
    obj2.append(Signal)
obj2.save(r"C:\FileNew.dat", overwrite=True, compression=compressionVal)
obj2.close
obj.close
```

  ## Traceback 1 (for target version v3.x)
```python
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v3.py", line 3528, in save
    address = channel.to_blocks(
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v2_v3_blocks.py", line 611, in to_blocks
    address = conversion.to_blocks(address, blocks, defined_texts, cc_map)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v2_v3_blocks.py", line 1290, in to_blocks
    self.unit_field = self.unit.encode("latin-1", "ignore")[:19]
AttributeError: 'bytes' object has no attribute 'encode'
```

  ## Traceback 1 (for target version v4.x)
```python
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v3.py", line 3528, in save
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v4.py", line 9172, in save
    address = channel.to_blocks(
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v4_blocks.py", line 1047, in to_blocks
    text=text.encode('utf-8', 'replace'),
AttributeError: 'bytes' object has no attribute 'encode'
```

  ## Code snippet 2
```python
# coding: latin-1
from asammdf import MDF, Signal
import asammdf
 
compressionVal = 1
newVersion = "3.30"
obj = MDF(r"C:\File.mf4")
obj.convert(version=newVersion)
obj.save(r"C:\FileNew.dat", overwrite=True, compression=compressionVal)
obj.close
```
  
  ## Traceback 2 (for target version v3.x)
```python
Traceback (most recent call last):
  File "C:\Code.py", line 8, in <module>
    obj.convert(version=newVersion)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\mdf.py", line 569, in convert
    cg_nr = out.append(
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v3.py", line 1390, in append
    conversion = conversion_transfer(signal.conversion)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\conversion_utils.py", line 39, in conversion_transfer
    unit = conversion.unit.strip(" \r\n\t\0").encode("latin-1")
TypeError: a bytes-like object is required, not 'str'
```

  ## Traceback 2 (for target version v4.x)
```python
Traceback (most recent call last):
  File "C:\Code.py", line 9, in <module>
    obj.save(r"C:\Users\u16j17\Desktop\Rohdaten_TestingV_Doppelkupplung\converted_to_4.00\4.0.mf4", overwrite=True, compression=compressionVal)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v4.py", line 9544, in save
    write(bytes(block))
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v4_blocks.py", line 1787, in __bytes__
    result = pack(fmt, *[getattr(self, key) for key in keys])
struct.error: pack expected 13 items for packing (got 16)
```

  ## Traceback from asammdf.exe (v4.x is OK, v3.x is throwing error)
```python
2021-07-26, 09:47:36
--------------------------------------------------------------------------------
<class 'Exception'> 
Traceback (most recent call last):
File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\gui\utils.py", line 381, in run
self.output = self._target(*self._args, **self._kwargs)
File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\mdf.py", line 569, in convert
cg_nr = out.append(
File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v3.py", line 1390, in append
conversion = conversion_transfer(signal.conversion)
File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\conversion_utils.py", line 39, in conversion_transfer
unit = conversion.unit.strip(" \r\n\t\0").encode("latin-1")
TypeError: a bytes-like object is required, not 'str'
```

# Description

Hi Daniel,

i tried to confert a v4.1 file into v3.x by using different ways and get some errors, see above. I will send you the scrambled file. The converion with asammdf.exe runs ok for version v4.x.
Would you also prefer Code 2 for file-converting?

(Some personal feedback: I think you have created a really good tool!)

Best regards,
Martin

**Comment by danielhrisca** [comment]
Hello Martin,

I will look into the problem but first, regarding your snippets, the file version needs to be given as string not as float (``"3.30"`` instead of ``3.3``)

**Comment by s9mahueb** [comment]
Hello Daniel, Thank you for the hint, I changed the code and updated the issue text :-) --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.07.21, 16:11 schrieb Daniel Hrisca ***@***.***>:

   
  Hello Martin, 
  I will look into the problem but first, regarding your snippets, the file version needs to be given as string not as float ("3.30" instead of 3.3)

**Comment by danielhrisca** [comment]
@s9mahueb please try 6.3.1.dev2

**Comment by s9mahueb** [comment]
Hi,
this
```python
# coding: latin-1
 
from asammdf import MDF, Signal
import asammdf
 
compressionVal = 1
newVersion = "3.00"
obj = MDF(r"C:\File.MF4")
obj.convert(version=newVersion)
obj.save(r"C:\NewFile.dat", overwrite=True, compression=compressionVal)
obj.close
```
rusults for newVersion = "3.00" and "4.00" :
```python
   obj.save(r"C:\NewFile.dat", overwrite=True, compression=compressionVal)
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\mdf_v4.py", line 9571, in save
    write(bytes(block))
  File "C:\Users\u16j17\AppData\Roaming\Python\Python39\site-packages\asammdf\blocks\v4_blocks.py", line 1792, in __bytes__
    result = pack(fmt, *[getattr(self, key) for key in keys])
struct.error: pack expected 13 items for packing (got 16)
```

This
```python
#coding: latin-1 
from asammdf import MDF, Signal
import asammdf
 
compressionVal = 1
newVersion = "3.30"
obj = MDF(r"C:\File.mf4")
obj2 = MDF(version = newVersion)
for Signal in obj:
    obj2.append(Signal)
obj2.save(r"C:\FileNew.dat", overwrite=True, compression=compressionVal)
obj2.close
obj.close
```
is running without errors for newVersion = "3.30" and "4.00". Perfect! But it's creating a mdf-File, not a dat-file as in filename. Is this desired?

Best regards,
Martin

**Comment by danielhrisca** [comment]
Hello Marin, please try development branch 6.3.2.dev1

**Comment by s9mahueb** [comment]
runs perfect. Thank you!
