### ISSUE TITLE
J1939 File Fails to Parse: canmatrix.canmatrix.J1939needsExtendedIdetifier

### ISSUE THREAD

**Issue by charlierance** [danielhrisca/asammdf#558]
# Python version
```
Python Version == 3.8
OS == Windows
asammdf version == 6.3.1
```

  ## Code snippet
```python
  def mf4_to_parquet(mf4_file: str, dbc_files: dict, file_path) -> str:
    with MDF(mf4_file) as mdf:
        mdf = mdf.extract_bus_logging(dbc_files)
        channels_db = mdf.channels_db
        del channels_db["time"]
        channels_db = {k: v for k, v in sorted(channels_db.items())}
        cols_new = []
        for sig in channels_db:
            CAN_no = [mdf.get(name=sig, group=sig_per_CAN[0], index=sig_per_CAN[1]).comment for sig_per_CAN in channels_db[sig]]
            CAN_no = [f"{sig}_{re.search('CAN[0-9]', sig_per_CAN).group()}" for sig_per_CAN in CAN_no]
            cols_new.extend(CAN_no)

        bad_dupes = {dupe: count_ - 1 for dupe, count_ in collections.Counter(cols_new).items() if count_ > 1}
        bad_dupes = [f"{dupe}_{count_}" for dupe in bad_dupes for count_ in range(bad_dupes[dupe])]
        cols_new = list(set(cols_new))
        cols_new.extend(bad_dupes)
        cols_new = sorted(cols_new)

        df = mdf.to_dataframe(time_as_date=True, keep_arrays=True)
        df.index = df.index.astype(str)
        df = df.sort_index(axis=1)
        df.columns = cols_new

        file_name = mf4_file.split(".")[0]
        df.to_parquet(os.path.join(file_path, f"{file_name}.parquet.gzip"), compression="gzip")

        return os.path.join(file_path, f"{file_name}.parquet.gzip")

def format_dbcs(dbc_dir: str) -> dict:
    dbcs = [(f"{dbc_dir}/{f}", 0) for f in os.listdir(dbc_dir) if ".dbc" in f]
    dbcs = {"CAN": dbcs}
    return dbcs
```
  
  ## Traceback
```
  Traceback (most recent call last):
  File "C:/Users/a/Documents/repos/pdm_experiments/mf4_experiements/mf4_to_parquet/mf4_to_parquet.py", line 152, in <module>
    mf4 = mf4_to_parquet("vehicle_vin_files_canlog_25270_20210720_130205.mf4", dbcs, os.getcwd())
  File "C:/Users/a/Documents/repos/pdm_experiments/mf4_experiements/mf4_to_parquet/mf4_to_parquet.py", line 14, in mf4_to_parquet
    mdf = mdf.extract_bus_logging(dbc_files)
  File "C:\Users\a\Documents\repos\pdm_experiments\venv\lib\site-packages\asammdf\mdf.py", line 4045, in extract_bus_logging
    out = self._extract_can_logging(
  File "C:\Users\a\Documents\repos\pdm_experiments\venv\lib\site-packages\asammdf\mdf.py", line 4115, in _extract_can_logging
    messages = {message.arbitration_id.pgn: message for message in dbc}
  File "C:\Users\a\Documents\repos\pdm_experiments\venv\lib\site-packages\asammdf\mdf.py", line 4115, in <dictcomp>
    messages = {message.arbitration_id.pgn: message for message in dbc}
  File "C:\Users\a\Documents\repos\pdm_experiments\venv\lib\site-packages\canmatrix\canmatrix.py", line 623, in pgn
    raise J1939needsExtendedIdetifier
canmatrix.canmatrix.J1939needsExtendedIdetifier
```
  
# Description

I have an MF4 file that I am parsing to extract the CAN data. With this I am applying multiple DBC's to all available channels, some of which are in the J1939 format. When I parse some of these files I get the above error.

**Comment by danielhrisca** [comment]
Looks like some kind of malformed DBC file

**Comment by charlierance** [comment]
I think you are correct, looking at a few of the files it looks like the odd one has a header malformation, closing issue for now

**Comment by pratik-mahamuni** [comment]
Hello. I am facing this same issue with the following details:
Python version: 3.10.11
asammdf: 7.3.12
canmatrix: 0.9.5

I dont think it is malformed DBC files; they were created using CANdb++ and open in multiple database editing software. Are there any other potential issues?
