### ISSUE TITLE
Unable to open MF4 attribute name not found error

### ISSUE THREAD

**Issue by RadhaSwathi** [danielhrisca/asammdf#573]
# Python version
_Please run the following snippet and write the output here_

```python
('python=3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.18362-SP0'
======================
'numpy=1.19.1'
'asammdf=5.21.0'
```
# Code 

 Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 307, in run
  File "asammdf\mdf.py", line 130, in __init__
  File "asammdf\blocks\mdf_v4.py", line 394, in __init__
  File "asammdf\blocks\mdf_v4.py", line 478, in _read
  File "asammdf\blocks\utils.py", line 700, in count_channel_groups
AttributeError: 'mmap.mmap' object has no attribute 'name'

Details: 2021-09-24, 12:36:20
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 307, in run
  File "asammdf\mdf.py", line 130, in __init__
  File "asammdf\blocks\mdf_v4.py", line 394, in __init__
  File "asammdf\blocks\mdf_v4.py", line 478, in _read
  File "asammdf\blocks\utils.py", line 700, in count_channel_groups
AttributeError: 'mmap.mmap' object has no attribute 'name'

--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\main.py", line 867, in open
  File "asammdf\gui\widgets\main.py", line 908, in open_file
  File "asammdf\gui\widgets\main.py", line 883, in _open_file
  File "asammdf\gui\widgets\file.py", line 160, in __init__
  File "asammdf\gui\utils.py", line 272, in run_thread_with_progress

Unable open MF4 file in both GUI and code getting above error.

**Comment by danielhrisca** [comment]
@RadhaSwathi  please update to the latest release and check if the issue still occurs
