### ISSUE TITLE
struct.error: unpack_from 

### ISSUE THREAD

**Issue by RobertMouncer** [danielhrisca/asammdf#576]
# Python version
```
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.21.2'
'asammdf=6.4.4'
```
# Code 

  ## MDF version
4.11

  ## Code snippet

from asammdf import MDF
```
mdf_path = '00000009.scrambled.mf4'
dbc_path = 'dbc_name'
mdf = MDF(mdf_path)
mdf.extract_bus_logging({'CAN':[(dbc_path, 0)]})
```

  ## Traceback
```
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 4050, in extract_bus_logging
    out = self._extract_can_logging(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 4178, in _extract_can_logging
    data_bytes = self.get(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6321, in get
    vals, timestamps, invalidation_bits, encoding = self._get_scalar(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 7369, in _get_scalar
    vals = extract(signal_data, 1, vals - vals[0])
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\blocks\mdf_v4.py", line 144, in extract
    (str_size,) = UINT32_uf(signal_data, offset)
struct.error: unpack_from requires a buffer of at least 106710 bytes for unpacking 4 bytes at offset 106706 (actual buffer size is 106706)
```
  
# Description

I have performed a MDF validator and all looks good, no errors.
I have tried opening the file in asammdf GUI and it opens, I can view the info panel but I cannot extract any of the data block (plot window, tab window) and I am greeted with the same issue.
I have performed a scramble but notice that the ID and datablocks remain so I can not share it publically.

**Comment by danielhrisca** [comment]
> I have performed a scramble but notice that the ID and datablocks remain so I can not share it publically.

The point of scrambling is to mangle all the text blocks so the channels names and comments are unusable for the external parties, but to preserve the internal file structure (ie. all other blocks remain the same) this way the file can be used for analysis.

**Comment by RobertMouncer** [comment]
> Does the error still appear with the development branch code?

Thank you for the reply.
I have not, what's the easiest way to install the development branch code to my site packages?

**Comment by danielhrisca** [comment]
``pip install -I --no-deps https://github.com/danielhrisca/asammdf/archive/development.zip``

**Comment by RobertMouncer** [comment]
I installed the development branch and this was the outcome:

```
mdf = MDF(mdf_path)
mdf.extract_bus_logging({'CAN':[(dbc, 0)]})
Traceback (most recent call last):
  File "C:\Users\robert.mouncer\AppData\Local\Programs\Python\Python38\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\robert.mouncer\Documents\GitHub Repos\Graphyt\venv\lib\site-packages\asammdf\mdf.py", line 4067, in extract_bus_logging
    out = self._extract_can_logging(
  File "C:\Users\robert.mouncer\Documents\GitHub Repos\Graphyt\venv\lib\site-packages\asammdf\mdf.py", line 4210, in _extract_can_logging
    bus_data_bytes = data_bytes[idx]
IndexError: index 11813 is out of bounds for axis 0 with size 11813
```

Here is the versioning again:
```
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19041-SP0'
'numpy=1.21.2'
'asammdf=7.0.0.dev19'
```

**Comment by RobertMouncer** [comment]
Sorry,
When I complete the same code outside of my virtual environment (same as in the raised issue) (issue above was in a different environment)
I get the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 4067, in extract_bus_logging
    out = self._extract_can_logging(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\site-packages\asammdf\mdf.py", line 4210, in _extract_can_logging
    bus_data_bytes = data_bytes[idx]
IndexError: index 11813 is out of bounds for axis 0 with size 11813
```

**Comment by danielhrisca** [comment]
It might be that the file is corrupted but I cannot tell without inspecting it. 

Keep in mind that MDFValidator does not check the actual samples of the channels, so for VLSD channels (like your case) it cannot tell if the referenced signal data block has enough bytes; at a glance it looks like the final sample is missing from the signal data block.

**Comment by RobertMouncer** [comment]
I notice on your profile you have your gmail listed, can I send the file to you via gmail as I don't want to publically post it?
I don't think the file is corrupt... Using another python package I am able to read in the mdf file and I notice that there are 30K+ data entries but asammdf only recognises the first 118113...

All your help is greatly appreciated.

**Comment by danielhrisca** [comment]
> I notice on your profile you have your gmail listed, can I send the file to you via gmail as I don't want to publically post it?

That's exactly why I shared the e-mail address :) thanks

**Comment by MatinF** [comment]
If you can share the original MF4 Robert we can also review at CSS

**Comment by danielhrisca** [comment]
So it turns out the regex used to detect the blocks in the unfinalized files was not robust enough. Some data bytes were mistakenly interpreted as block headers. Please try the latest development branch code

**Comment by RobertMouncer** [comment]
Issue resolved.
Thank you very mich both for your help 😄
