### ISSUE TITLE
mdf.filter() got an error due to timestamp

### ISSUE THREAD

**Issue by mrmuyi** [danielhrisca/asammdf#642]
('python=3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.22.1'
'asammdf=7.0.7'

CODE:
from asammdf import MDF
mdf_data= MDF('rec_4021015_2022-01-06-17_07_35_1_sorted.dat')
filer_data = mdf_data.filter(['VehSpdAvg:CAN2','VehOdo:CAN1'])

Traceback (most recent call last):
  File "D:\A_YPC\Mine_PY\00_MODULE\01 DEAL_MDF\SORTED_MDF_DEAL_20220202\testasammdf.py", line 23, in <module>
    filer_data = mdf_data.filter(['VehSpdAvg:CAN2','VehOdo:CAN1'])
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\mdf.py", line 1847, in filter
    mdf.header.start_time = self.header.start_time
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\blocks\v2_v3_blocks.py", line 2918, in start_time
    timestamp = int(timestamp.timestamp() * 10**9)
OSError: [Errno 22] Invalid argument

_Please describe the issue here._
Something wrong with mdf_data.filter() when int(timestamp.timestamp() * 10**9).
'''
OSError: [Errno 22] Invalid argument
'''

**Comment by mrmuyi** [comment]
[rec_4021015_2022-01-06-17_07_35_1_sorted.zip](https://github.com/danielhrisca/asammdf/files/7987319/rec_4021015_2022-01-06-17_07_35_1_sorted.zip)

**Comment by danielhrisca** [comment]
shoudl work with 7.1.0
