### ISSUE TITLE
Samples and timestamps length mismatch

### ISSUE THREAD

**Issue by zariiii9003** [danielhrisca/asammdf#666]
# Python version
('python=3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19042-SP0'
'numpy=1.22.2'
'asammdf=7.0.7'

# Code 

  ## MDF version
  4.10

  ## Code snippet
```python3
import asammdf

if __name__ == "__main__":
    mdf_orig = asammdf.MDF(r"C:\Path\To\My\File.mf4")

    # selection = mdf_orig.select(["MySignalName"])
    sig = mdf_orig.get("MySignalName")
```
  
  ## Traceback
```
asammdf - ERROR - MySignalName samples and timestamps length mismatch (4787 vs 0)
NoneType: None
Traceback (most recent call last):
  File "D:\Path\To\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6525, in get
    res = Signal(
  File "D:\Path\To\venv\lib\site-packages\asammdf\signal.py", line 129, in __init__
    raise MdfException(message)
asammdf.blocks.utils.MdfException: MySignalName samples and timestamps length mismatch (4787 vs 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Path\To\scratch.py", line 15, in <module>
    sig = mdf_orig.get("MySignalName")
  File "D:\Path\To\venv\lib\site-packages\asammdf\blocks\mdf_v4.py", line 6545, in get
    debug_channel(self, grp, channel, dependency_list)
  File "D:\Path\To\venv\lib\site-packages\asammdf\blocks\utils.py", line 820, in debug_channel
    parents, dtypes = mdf._prepare_record(group)
ValueError: too many values to unpack (expected 2)
```
  
# Description
I get an exception when i use `get()`.
But: I do not get any exceptions when i run `select()` before calling `get()`. I do not get any exceptions when i plot the signal in the GUI. I do not get any exceptions when i call `get()` on the scrambled version of this file.

**Comment by danielhrisca** [comment]
Hello @zariiii9003 please send the file privately over e-mail (I can assure you that I will not share it with other persons)
