### ISSUE TITLE
No module named 'asammdf.blocks.cutils' when installing from development branch on Ubuntu

### ISSUE THREAD

**Issue by ptoews** [danielhrisca/asammdf#717]
I cannot install the latest development version. After cloning and changing to the development branch, I created a fresh venv and ran `pip install .` with the following output, showing no warnings or errors:

```
~/Downloads/asammdf$ pip install .
Processing /home/philipp/Downloads/asammdf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting isal; platform_machine == "x86_64" or platform_machine == "AMD64"
  Using cached isal-0.11.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pandas
  Using cached pandas-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting numexpr
  Using cached numexpr-2.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
Collecting lz4
  Using cached lz4-4.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting numpy>=1.21
  Using cached numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
Collecting canmatrix[arxml,dbc]>=0.8
  Using cached canmatrix-0.9.5-py2.py3-none-any.whl (320 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting attrs>=19.2.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Processing /home/philipp/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Collecting lxml; extra == "arxml"
  Using cached lxml-4.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Building wheels for collected packages: asammdf
  Building wheel for asammdf (PEP 517) ... done
  Created wheel for asammdf: filename=asammdf-7.1.0.dev56-cp38-cp38-linux_x86_64.whl size=761693 sha256=612dee7cf7ea1ddeddb9146d885177e1373048b1a9123c1d4b86bda555f33225
  Stored in directory: /tmp/pip-ephem-wheel-cache-zccs909i/wheels/da/54/39/592b6f672c4efc11fd46f66d43f78245e5421f3d6c936f24a2
Successfully built asammdf
Installing collected packages: typing-extensions, isal, six, python-dateutil, numpy, pytz, pandas, pyparsing, packaging, numexpr, lz4, click, attrs, future, lxml, canmatrix, asammdf
Successfully installed asammdf-7.1.0.dev56 attrs-21.4.0 canmatrix-0.9.5 click-8.1.3 future-0.18.2 isal-0.11.1 lxml-4.9.0 lz4-4.0.1 numexpr-2.8.1 numpy-1.22.4 packaging-21.3 pandas-1.4.2 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.1 six-1.16.0 typing-extensions-4.2.0
```

However, when opening a python shell and trying to import asammdf, I get this:

```
~/Downloads/asammdf$ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asammdf
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philipp/Downloads/asammdf/asammdf/__init__.py", line 17, in <module>
    from .mdf import MDF, SUPPORTED_VERSIONS
  File "/home/philipp/Downloads/asammdf/asammdf/mdf.py", line 42, in <module>
    from .blocks.mdf_v2 import MDF2
  File "/home/philipp/Downloads/asammdf/asammdf/blocks/mdf_v2.py", line 9, in <module>
    from .mdf_v3 import MDF3
  File "/home/philipp/Downloads/asammdf/asammdf/blocks/mdf_v3.py", line 49, in <module>
    from .cutils import get_channel_raw_bytes
ModuleNotFoundError: No module named 'asammdf.blocks.cutils'
```
This cutils file only exists as a .c file. I found this related issue: https://github.com/danielhrisca/asammdf/issues/585#issuecomment-959050559, however the answer suggests installing Visual Studio Build Tools, which is unfortunately not possible on my Ubuntu machine.

**Comment by danielhrisca** [comment]
```
apt install build-essential python3-dev
```

**Comment by ptoews** [comment]
These packages were already installed

**Comment by danielhrisca** [comment]
you can try this command for installing the development branch

```python
pip install https://github.com/danielhrisca/asammdf/archive/development.zip
```

if it still does not work then you need to figure out what part of your setup is not correctly configured to be able to compile Python C extensions (see https://docs.python.org/3/extending/extending.html#compilation-and-linkage)
