### ISSUE TITLE
Error 'WindowsPath' object has no attribute 'read' - MDF4 file compressed as .gz

### ISSUE THREAD

**Issue by bernard-claus** [danielhrisca/asammdf#725]
# Python version
3.7.0
# Code 
```python
from asammdf import MDF
import os
import gzip

def create_mdf_object(filepath):
    if not os.path.exists(filepath):
        raise FileNotFoundError(f'Could not find or access desired file: {filepath}')
    else:
        if os.path.splitext(filepath)[1] == ".gz" or os.path.splitext(filepath)[1] == ".gzip":
            return MDF(gzip.GzipFile(filepath, 'rb'))
        else:
            return MDF(filepath)
```
  ## MDF version
  4.10

  ## Code snippet
  ```MDF(gzip.GzipFile(filepath, 'rb'))```
  
  ## Traceback
  ```Traceback (most recent call last):
  File "c:\Users\FC00001\Documents\Stellantis\Programação\Python\data-conversion-api\mdf_utilities\mdf_api.py", line 37, in list_channels
    mdf_object = create_mdf_object(filepath)
  File "c:\Users\FC00001\Documents\Stellantis\Programação\Python\data-conversion-api\mdf_utilities\mdf_api.py", line 23, in create_mdf_object
    return MDF(gzip.GzipFile(filepath, 'rb'))
  File "C:\Users\FC00001\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\mdf.py", line 250, in __init__
    name.write_bytes(name.read())
AttributeError: 'WindowsPath' object has no attribute 'read'
```
  
# Description
Trying to read an MDF4 file which is compressed as .gz returns the forementioned error. File is working fine - decompressing works fine and also running the following code returns all data inside the file:
```
import gzip
path = r"filename.dat.gz"
file = gzip.GzipFile(path)
file.read()
```

**Comment by bernard-claus** [comment]
> Hello Bernard,
> 
> please try the development branch code

This worked perfectly. Thank you very much!
