### ISSUE TITLE
array-shape mismatch in array 239

### ISSUE THREAD

**Issue by Taha2312** [danielhrisca/asammdf#74]
Python version 3.6

```python
('python=3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) '
 '[MSC v.1900 64 bit (AMD64)]')
'os=Windows-10-10.0.16299-SP0'
'numpy=1.14.2'
'asammdf=3.5.0'```

  ## MDF version
4.10

  ## Code snippet
from asammdf import MDF

mdf = MDF(r'C:\Users\User1\Desktop\test.mf4')
mdf.resample(1).save(r'C:\Users\User1\Desktop\abc.mf4')
  
  ## Traceback
Traceback (most recent call last):

  File "<ipython-input-38-ac3f32e0e9c7>", line 1, in <module>
    runfile('C:/Users/p368824/.spyder-py3/asammdf.py', wdir='C:/Users/p368824/.spyder-py3')

  File "C:\Users\p368824\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\p368824\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/p368824/.spyder-py3/asammdf.py", line 4, in <module>
    mdf.resample(1).save(r'C:\Users\p368824\Desktop\Messungen 11. Juni\test\abc.mf4')

  File "C:\Users\p368824\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf.py", line 2310, in resample
    common_timebase=True,

  File "C:\Users\p368824\AppData\Local\Continuum\anaconda3\lib\site-packages\asammdf\mdf_v4.py", line 2983, in append
    samples = fromarrays(fields, dtype=types)

  File "C:\Users\p368824\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\records.py", line 628, in fromarrays
    raise ValueError("array-shape mismatch in array %d" % k)

ValueError: array-shape mismatch in array 239
  
# Description
When I try to resample a mdf file, it occurs the error above. How can I solve this Problem? Normal reading and saving works properly, but I need to resample my mdf file.

**Comment by danielhrisca** [comment]
Hello @Taha2312,

could you send the file by e-mail?

**Comment by danielhrisca** [comment]
I've tried resampling on my files and couldn't reproduce your error. I did found a different error and that one got fixed.

**Comment by Taha2312** [comment]
Hello Daniel,


Actually, my .mf4 file is about 1 GB. That's the reason why I want to resample them. I don't know how I can provide you my file. Do you have an idea?

Thank you in advance.


Best regards,


Taha Agacdograyan



________________________________
Von: Daniel Hrisca <notifications@github.com>
Gesendet: Dienstag, 19. Juni 2018 08:56
An: danielhrisca/asammdf
Cc: Taha2312; Mention
Betreff: Re: [danielhrisca/asammdf] array-shape mismatch in array 239 (#74)


I've tried resampling on my files and couldn't reproduce your error. I did found a different error and that one got fixed.

**Comment by danielhrisca** [comment]
You could use Google Drive to upload the large file. Please write me an e-mail with your info (daniel.hrisca at gmail.com)

**Comment by danielhrisca** [comment]
this was solved in https://github.com/danielhrisca/asammdf/commit/5c1906b8837316b128630e8434440fd5b0e9b63b
