### ISSUE TITLE
asammdf GUI missing libraries

### ISSUE THREAD

**Issue by tistelac** [danielhrisca/asammdf#841]
# Python version
('python=3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 '
'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.22.4'
'asammdf=7.3.7'

  ## Traceback
ModuleNotFoundError: No module named 'PySide6'
ModuleNotFoundError: No module named 'pyqtlet2'
QWidget: Must construct a QApplication before a QWidget  
File "C:\Program Files\Python310\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 36, in <module>    raise QtModuleNotInstalledError(qtpy.QtModuleNotInstalledError: The QtWebEngineWidgets module was not found. It must be installed separately as PyQtWebEngine.

# Description

asammdf module installs without any errors, grabbing modules as needed. 
GUI however still needs some modules, and trying to pip install these modules is not working, some dependencies with PyQtWebEngine, QWidget 

Please advice, thank you

**Comment by danielhrisca** [comment]
pip install asammdf[gui]

**Comment by tistelac** [comment]
I did pip install asammdf, when running the gui I still get this:

C:\Program Files\Python310\lib\site-packages\qtpy\__init__.py:267: RuntimeWarning: Selected binding "pyside6" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
QWidget: Must construct a QApplication before a QWidget

## "traceback" from pip install asammdf
Requirement already satisfied: asammdf[GUI] in c:\program files\python310\lib\site-packages (7.3.6)
Requirement already satisfied: python-dateutil in c:\users\cniesse\appdata\roaming\python\python310\site-packages (from asammdf[GUI]) (2.8.2)
Requirement already satisfied: numexpr in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (2.8.1)
Requirement already satisfied: canmatrix[arxml,dbc]>=0.8 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (0.9.5)
Requirement already satisfied: numpy>=1.23.0 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (1.24.2)
Requirement already satisfied: pandas in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (1.4.2)
Requirement already satisfied: lz4 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (4.0.1)
Requirement already satisfied: isal in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (0.11.1)
Requirement already satisfied: typing-extensions in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (4.2.0)
Requirement already satisfied: PySide6 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (6.4.3)
Requirement already satisfied: natsort in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (8.1.0)
Requirement already satisfied: pyqtgraph>=0.12.4 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (0.12.4)
Requirement already satisfied: psutil in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (5.9.1)
Requirement already satisfied: pyqtlet2>=0.8.0 in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (0.9.3)
Requirement already satisfied: lxml in c:\program files\python310\lib\site-packages (from asammdf[GUI]) (4.9.0)
Requirement already satisfied: future in c:\program files\python310\lib\site-packages (from canmatrix[arxml,dbc]>=0.8->asammdf[GUI]) (0.18.2)
Requirement already satisfied: attrs>=19.2.0 in c:\program files\python310\lib\site-packages (from canmatrix[arxml,dbc]>=0.8->asammdf[GUI]) (21.4.0)
Requirement already satisfied: six in c:\users\cniesse\appdata\roaming\python\python310\site-packages (from canmatrix[arxml,dbc]>=0.8->asammdf[GUI]) (1.16.0)
Requirement already satisfied: click in c:\program files\python310\lib\site-packages (from canmatrix[arxml,dbc]>=0.8->asammdf[GUI]) (8.1.3)
Requirement already satisfied: QtPy>=2.0.1 in c:\program files\python310\lib\site-packages (from pyqtlet2>=0.8.0->asammdf[GUI]) (2.3.0)
Requirement already satisfied: packaging in c:\users\cniesse\appdata\roaming\python\python310\site-packages (from numexpr->asammdf[GUI]) (21.3)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python310\lib\site-packages (from pandas->asammdf[GUI]) (2022.1)
Requirement already satisfied: shiboken6==6.4.3 in c:\program files\python310\lib\site-packages (from PySide6->asammdf[GUI]) (6.4.3)
Requirement already satisfied: PySide6-Addons==6.4.3 in c:\program files\python310\lib\site-packages (from PySide6->asammdf[GUI]) (6.4.3)
Requirement already satisfied: PySide6-Essentials==6.4.3 in c:\program files\python310\lib\site-packages (from PySide6->asammdf[GUI]) (6.4.3)
Requirement already satisfied: colorama in c:\program files\python310\lib\site-packages (from click->canmatrix[arxml,dbc]>=0.8->asammdf[GUI]) (0.4.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\cniesse\appdata\roaming\python\python310\site-packages (from packaging->numexpr->asammdf[GUI]) (3.0.9)

**Comment by danielhrisca** [comment]
try with PySide6 6.3.1

**Comment by danielhrisca** [comment]
Something weird is going on on your setup. You should create an isolated virtual environment and install asammdf with the command I wrote earlier, then run the app from that environment

**Comment by gpollo** [comment]
I won't create an other issue right now, but I have similar problems. With Python 3.10.2, under Windows and a fresh virtual environment, `asammdf.exe` won't run
```
$ python -m venv .venv
$ source .venv/Scripts/activate
$ pip install asammdf[gui]
$ asammdf.exe
...
ModuleNotFoundError: No module named 'pyqtgraph.canvas.CanvasTemplate_pyqt5'
```

**Comment by danielhrisca** [comment]
PySide6 6.5 is not working, downgrade

**Comment by ChrisH1108** [comment]
I have the same problem on my windows environment. I can build the current development or master branch, but run into issues try to running "asammdf"
I down-/upgraded the depending libraries, but with no luck and the following error:
ModuleNotFoundError: No module named 'pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_generic'

Please state which libs AND version must installed to run the gui

Thanks in advance
Christian

**Comment by danielhrisca** [comment]
the development branch works right now

#. download and extract the [development zip](https://github.com/danielhrisca/asammdf/archive/development.zip)
#. in the asammdf folder run `python setup.py bdist_wheel`
#. create a new virtual environment `python -m venv __asammdffgui`
#. activate the environment `__asammdfgui\Scripts\activate`
#. install the new wheel  `pip install dist\asammdf-7.3.13.dev7-cp310-cp310-win_amd64.whl[gui]`
#. run the gui script `__asammdfgui\Scripts\asammdf.exe`

**Comment by ChrisH1108** [comment]
I did a pull on the latest development branch and build it. This works fine without a virtual environment.

**Comment by eblis** [comment]
Version 7.3.12 has the problem with 'pyqtgraph.console.template_generic' on my machine as well.

```python
Traceback (most recent call last):
  File "C:\Users\F4GWHKR\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\F4GWHKR\.pyenv\pyenv-win\versions\3.9.13\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\Scripts\asammdf.exe\__main__.py", line 4, in <module>
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\asammdfgui.py", line 14, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\main.py", line 21, in <module>
    from .file import FileWidget
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\file.py", line 51, in <module>
    from .mdi_area import get_functions, MdiAreaWidget, WithMDIArea
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\mdi_area.py", line 48, in <module>
    from .numeric import Numeric
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\numeric.py", line 25, in <module>
    from asammdf.gui.widgets.plot import PlotSignal
  File "C:\Users\F4GWHKR\AppData\Local\pypoetry\Cache\virtualenvs\pdp-v6oKkWR0-py3.9\lib\site-packages\asammdf\gui\widgets\plot.py", line 33, in <module>
    import pyqtgraph.console.template_generic
ModuleNotFoundError: No module named 'pyqtgraph.console.template_generic'
```

 I have the following libs installed:
```python
asammdf 7.3.12 ASAM MDF measurement data file parser
├── canmatrix >=0.8
│   ├── attrs >=19.2.0
│   ├── click *
│   │   └── colorama *
│   ├── future *
│   ├── lxml *
│   └── six *
├── isal *
├── lz4 *
├── numexpr *
│   └── numpy >=1.13.3
├── numpy >=1.23.0
├── pandas *
│   ├── numpy >=1.20.3
│   ├── numpy >=1.21.0 (circular dependency aborted here)
│   ├── python-dateutil >=2.8.2
│   │   └── six >=1.5
│   ├── pytz >=2020.1
│   └── tzdata >=2022.1
├── python-dateutil *
│   └── six >=1.5
└── typing-extensions *
matplotlib 3.7.1 Python plotting package
├── contourpy >=1.0.1
│   └── numpy >=1.16
├── cycler >=0.10
├── fonttools >=4.22.0
├── importlib-resources >=3.2.0
│   └── zipp >=3.1.0
├── kiwisolver >=1.0.1
├── numpy >=1.20
├── packaging >=20.0
├── pillow >=6.2.0
├── pyparsing >=2.3.1
└── python-dateutil >=2.7
    └── six >=1.5
[...]
psutil 5.9.5 Cross-platform lib for process and system monitoring in Python.
pyarrow 12.0.0 Python library for Apache Arrow
└── numpy >=1.16.6
pyorc 0.8.0 Python module for reading and writing Apache ORC file format.
└── tzdata >=2020.5
pyqtgraph 0.13.3 Scientific Graphics and GUI Library for Python
└── numpy >=1.20.0
pyqtlet2 0.9.3 Bringing leaflet maps to Python Qt bindings
└── qtpy >=2.0.1
    └── packaging *
pyside6 6.3.1 Python bindings for the Qt cross-platform application and UI framework
├── pyside6-addons 6.3.1
│   ├── pyside6-essentials 6.3.1
│   │   └── shiboken6 6.3.1
│   └── shiboken6 6.3.1 (circular dependency aborted here)
├── pyside6-essentials 6.3.1
│   └── shiboken6 6.3.1
└── shiboken6 6.3.1
```

**Comment by tk-130** [comment]
I also encountered a similar phenomenon. And I have confirmed that installing pyqtgraph with 0.13.1 eliminates a phenomenon similar to the one you have discovered.

**Comment by myrthel** [comment]
I had this message:
`.\Python310\lib\site-packages\qtpy\__init__.py:214:` RuntimeWarning: Selected binding "pyside6" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
QWidget: Must construct a QApplication before a `QWidget`
pip -m uninstall pyqt5 did for me the trick in this case

**Comment by ChrisH1108** [comment]
Use the latest committed version from the development branch. This works for me

**Comment by danielhrisca** [comment]
With the latest release 7.3.16 running pip install asammdf[gui] will install the correct pinned version
