### ISSUE TITLE
ASAMMDF GUI report "typeError: data type '>i64' not understood"

### ISSUE THREAD

**Issue by mrmuyi** [danielhrisca/asammdf#842]
python :3.10.0
asammdf:7.3.3
OS: windows 10 64bit
original file send by email.
 
# Description
using the asammdf gui to open .dat file, report error as follows:
 Error: <class 'Exception'>	 
Traceback (most recent call last):
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\gui\utils.py", line 364, in run
    self.output = self._target(*self._args, **self._kwargs)
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\mdf.py", line 348, in __init__
    self._mdf = MDF3(name, channels=channels, **kwargs)
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\blocks\mdf_v3.py", line 267, in __init__
    self._read(mapped=True, progress=progress)
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\blocks\mdf_v3.py", line 949, in _read
    self._prepare_record(grp)
  File "C:\Users\SAIC_dataParse\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\blocks\mdf_v3.py", line 567, in _prepare_record
    new_ch.dtype_fmt = dtype(
TypeError: data type '>i64' not understood

**Comment by mrmuyi** [comment]
I have tried the development branch code, it runs ok and has no errors!
Then I close the issue, thanks~

**Comment by mrmuyi** [comment]
Daniel,
       I wander when will the change implemented in the master version? The new version 7.3.9 did not fix the issue.
       May I have the .whl file of the development branch, thanks!
















At 2023-03-29 17:36:08, "Daniel Hrisca" ***@***.***> wrote:

@mrmuyi please try the development branch code

**Comment by danielhrisca** [comment]
@mrmuyi the fix is already included in 7.3.9 (https://github.com/danielhrisca/asammdf/commit/01567a5663b44e9d0a24b946059feb20a2d0ebf9) make sure that you are really installing this in your environment
