### ISSUE TITLE
Several of `ModuleNotFoundError`, after installing via pip

### ISSUE THREAD

**Issue by raleighlittles** [danielhrisca/asammdf#868]
# Python version
_Please run the following snippet and write the output here_
```python
'python=3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]'
'os=Linux-5.19.0-43-generic-x86_64-with-glibc2.35'
'numpy=1.24.3'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.12'
```
# Code 

  ## MDF version
  _please write here the file version (you can run ``print(MDF(file).version)``)

  ## Code snippet
  _please write here the code snippet that triggers the error_
  
  ## Traceback
 
```
Traceback (most recent call last):
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/plot.py", line 21, in <module>
    import pyqtgraph.canvas.CanvasTemplate_pyside6
ModuleNotFoundError: No module named 'pyqtgraph.canvas.CanvasTemplate_pyside6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raleigh/.local/bin/asammdf", line 5, in <module>
    from asammdf.gui.asammdfgui import main
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/asammdfgui.py", line 14, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/main.py", line 21, in <module>
    from .file import FileWidget
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/file.py", line 51, in <module>
    from .mdi_area import get_functions, MdiAreaWidget, WithMDIArea
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/mdi_area.py", line 48, in <module>
    from .numeric import Numeric
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/numeric.py", line 25, in <module>
    from asammdf.gui.widgets.plot import PlotSignal
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/plot.py", line 33, in <module>
    import pyqtgraph.console.template_generic
ModuleNotFoundError: No module named 'pyqtgraph.console.template_generic'

```
  
# Description

The fastest way to debug is to have the original file. For data protection you can use the static 
method _scramble_ to scramble all text blocks, and send the scrambled file by e-mail.

_Please describe the issue here._

Tried to install via pip instructions. 

![image](https://github.com/danielhrisca/asammdf/assets/2137201/e17e9958-88f4-4785-b445-151c1e5610c1)

Installation was fine, but when I tried to run `asammdf` as instructed to, in the command line, I get this error:

```
ldf is not supported
xls is not supported
xlsx is not supported
===== 2023.06.15 23:06:30 =====
Traceback (most recent call last):
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/plot.py", line 21, in <module>
    import pyqtgraph.canvas.CanvasTemplate_pyside6
ModuleNotFoundError: No module named 'pyqtgraph.canvas.CanvasTemplate_pyside6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raleigh/.local/bin/asammdf", line 5, in <module>
    from asammdf.gui.asammdfgui import main
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/asammdfgui.py", line 14, in <module>
    from asammdf.gui.widgets.main import MainWindow
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/main.py", line 21, in <module>
    from .file import FileWidget
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/file.py", line 51, in <module>
    from .mdi_area import get_functions, MdiAreaWidget, WithMDIArea
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/mdi_area.py", line 48, in <module>
    from .numeric import Numeric
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/numeric.py", line 25, in <module>
    from asammdf.gui.widgets.plot import PlotSignal
  File "/home/raleigh/.local/lib/python3.10/site-packages/asammdf/gui/widgets/plot.py", line 33, in <module>
    import pyqtgraph.console.template_generic
ModuleNotFoundError: No module named 'pyqtgraph.console.template_generic'
```

I'm on Ubuntu 22.04 LTS.

**Comment by jrask** [comment]
I have the exact same issue on Mac M1 13.6

**Comment by danielhrisca** [comment]
With the latest release 7.3.16 running `pip install asammdf[gui]` will install the correct pinned version
