### ISSUE TITLE
Batch export from GUI -  'WindowsPath' object has no attribute 'configure'

### ISSUE THREAD

**Issue by mlauterbacher** [danielhrisca/asammdf#880]
# Python version
('python=3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.22621-SP0'
'numpy=1.24.4'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.3.13'

# Code 

  ## MDF version
  4.10

  ## Code snippet
  none, GUI triggered
  
  ## Traceback
Traceback (most recent call last):
  File "C:\Users\mlauterbacher\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\gui\utils.py", line 251, in run
    result = self.function(*self.args, **self.kwargs)
  File "C:\Users\mlauterbacher\AppData\Local\Programs\Python\Python310\lib\site-packages\asammdf\gui\widgets\batch.py", line 1460, in apply_processing_thread
    mdf_file.configure(
AttributeError: 'WindowsPath' object has no attribute 'configure'
  
# Description

In asammdf GUI: When I try to export multiple files in batch mode. After click on "Apply". Output format and other parameters irrelevant.

**Comment by mlauterbacher** [comment]
Same holds true for linux (tested with WSL): AttributeError: 'PosixPath' object has no attribute 'configure'

**Comment by danielhrisca** [comment]
@mlauterbacher please try the latest release 7.3.16

**Comment by mlauterbacher** [comment]
I tested Version 7.3.16 on Windows and WSL. The described issue remains, batch conversion is not possible.

**Comment by danielhrisca** [comment]
@mlauterbacher please try again

**Comment by mlauterbacher** [comment]
I just tested version 8.0.1 on Windows and the issue does no longer occur. Batch export works fine. Thank you.
