### ISSUE TITLE
Problem in concatenating a list of asammdf objects

### ISSUE THREAD

**Issue by masoomk87** [danielhrisca/asammdf#902]
# Python version
_Please run the following snippet and write the output here_
```
('python=3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 '
 'bit (AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.25.1'
'asammdf=7.3.12'
```
# Code 

  ## MDF version
4.10

  ## Code snippet
mdf1.groups = [group for group in mdf1.groups if group.data_group is not None]
mdf2.groups = [group for group in mdf1.groups if group.data_group is not None]
MDF.concatenate([mdf1, mdf2])
  
  ## Traceback
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\MyPythonProjects\DataNinja\venv\Lib\site-packages\asammdf\mdf.py", line 2571, in concatenate
    max_size = max(
               ^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

  
# Description

When I try to concatenate a list of asammdf object, I get the error mentioned in the Traceback. I have ensured that the structure of both the mf4 file is identical. When I try to use merge on the same mf4 file, then there is no problem

There are more than 8000 channels in my mf4 file. What could be the quickest way to determine which channel is having a problem with concatenate ? 

While saving the mf4 files to disk, I use this attribute : mdf.save('FullPath', overwrite=True, compression=3)

**Comment by masoomk87** [comment]
I realized that the datatype of channels being concatenated were different, which caused the script the fail. After fixing them, the script worked fine
